```{r}
setwd("[please change it into your own path]") 
# Please change it to your own path, where file 'Supplementary Data.csv', 'EEZ_mangroveloss_final.csv',  'Supplementary Data of Fig. S6.csv' and 'implement cost.csv' exist.
```

```{r}
library("dplyr")
library("tidyr")
library("ggplot2")
library("rstatix")
library("ggpmisc")
library("ggpubr")
library("lme4")
library("ggrepel")
library("ggalluvial")
library("reshape2")
library("introdataviz")
library("multcompView")
library("car")
library("FSA")
library("rcompanion")
library("nlraa")
library("agricolae")
```


```{r}
data=read.csv("Supplementary Data.csv",stringsAsFactors = FALSE,fileEncoding="latin1")

data=data%>%
  filter(ID<1000)%>%  # delete abnormal data
  filter(re_af!="")%>%
  filter(plant_nature!="")

# colnames(data)

colnames(data)[c(19:24,26,28:33,35)]

colnames(data)[c(19:24,26,28:33,35)]=c("BC_mean","ABC_mean","BBC_mean",
                                    "SCS_mean","SCS_mean_100","SCS_increase_all",
                                       "SC_mean","TECS_mean",
                                       "salinity_pore",
                                       "sand","silt","clay",
                                       "TN_mean","N.concentration_mean")  ## simplify column names
colnames(data)[c(19:24,26,28:33,35)]


sitenumber=nrow(data%>%filter(group=="restored")%>%filter(re_af!="")%>%filter(ABC_mean!=""|BBC_mean!=""|SCS_mean_100!=""|TECS_mean!=""))
region=data%>%filter(group=="restored")%>%filter(re_af!="")%>%filter(ABC_mean!=""|BBC_mean!=""|SCS_mean_100!=""|TECS_mean!="")%>%filter(Region!="")
round(table(region$Region)/nrow(region)*100,2)
reference=nrow(unique(data%>%select(Author,Reference)))+6

reference=unique(data%>%select(ID,group,Author,Reference))

```


```{r}
### Figure 1 ###
carbon=data
carbon[is.na(carbon)]=0
carbon=carbon[carbon$rehab_type!="",]
carbon=carbon[carbon$group=="restored",]
n=nrow(carbon)
carbon$all=rep(6,n)
carbon$region=factor(1:n)

mytheme=theme_bw()+
  theme(axis.text = element_text(family = "Helvetica",size=7),
  axis.text.x=element_text(face="plain",family = "Helvetica",size=7), 
        axis.text.y=element_text(face="plain",family = "Helvetica",size=7), 
        axis.title.y=element_text(face="plain",family = "Helvetica",size=7), 
        axis.title.x=element_text(face="plain",family = "Helvetica",size=7),  
        plot.title=element_text(hjust=0.5,vjust=0,family = "Helvetica",size=7),
        legend.text = element_text(family = "Helvetica",size=7),
        legend.title = element_text(face="plain",family = "Helvetica",size=7),
        panel.border = element_rect(fill=NA, size=0.4),
        legend.position = "bottom",
        strip.text.x = element_text(family = "Helvetica",size=7),
        panel.grid.major =element_blank(), 
        panel.grid.minor = element_blank(),
        axis.ticks = element_line(colour = 'black', size = 0.3))

world = map_data('world')
p = ggplot(world, aes(long, lat)) +
    geom_map(map=world, aes(map_id=region), 
             fill="lightgrey", color="grey") +
    coord_quickmap() +
    scale_x_continuous(expand = c(0, 0))+
    scale_y_continuous(expand = c(0, 0),limits = c(-42,35))+
    scale_size(limits = c(0,500))+
    geom_point(data=subset(carbon,ABC_mean!=0),
               aes(x=Longitude,y=Latitude,
                   shape=re_af,size=ABC_mean,color=Age),
               alpha=0.5) +
    guides(shape = guide_legend(nrow = 2,
                                title="Rehabitation type",
                                override.aes = list(size = c(5,5))),
           size=guide_legend(title=expression(atop("",
                                                   atop(textstyle("Carbon density"),
                                                        atop(textstyle("(Mg C ha"^-1*")")))))))+
  labs(color=expression(atop("",atop(textstyle("Age"),
                                     atop(textstyle("(Year)"))))))+
  mytheme+
    theme(panel.grid.major =element_blank(),
        panel.grid.minor = element_blank(),
        axis.title.x = element_text(color="white"),
        legend.background = element_blank(),
        legend.position = "bottom")+
    scale_colour_gradient(high = "#006400",low = "#89C35C") +
    xlab("Longitude")+
    ylab("Latitude")+
  annotate("text", x =-100, y =0,label="Ⅰ",parse = T,family="serif",size=2)+
  annotate("text", x =-20, y =10,label="Ⅱ",parse = T,family="serif",size=2)+
  annotate("text" ,x =60 ,y =10, label="Ⅲ",parse = T,family="serif",size=2)+
  annotate("text", x =90,y =15 , label="Ⅳ",parse=T,family="serif",size=2)+
  annotate("text", x =115 ,y =10, label="Ⅴ",parse = T,family="serif",size=2)

p1 =ggplot(data=subset(carbon,ABC_mean!=0),
           aes(x=Latitude,y=ABC_mean))+
    geom_point(aes(x=Latitude,y=ABC_mean,
                   size=ABC_mean,shape=re_af,color=Age),alpha=0.5,size=2) +
    geom_smooth(color="#006400",alpha=0.2,size=0.5)+
    guides(color = FALSE)+ 
    scale_x_continuous(expand = c(0, 0),limits = c(-42,35))+
  mytheme+
    theme(
        axis.title.y = element_blank(),
        axis.text.y = element_blank(),
        axis.title.x = element_text(color="white"),
        panel.grid.major =element_blank(), 
        panel.grid.minor = element_blank(),
        legend.title=element_blank(),
        legend.background = element_blank(),
        legend.position ="bottom")+
    scale_colour_gradient(high = "#006400", low = "#89C35C")+
  scale_y_continuous(limits = c(0,260),breaks=seq(0,250, by = 50) )+
  coord_flip()

p2 = ggplot(world, aes(long, lat)) +
    geom_map(map=world, 
             aes(map_id=region), fill="lightgrey", color="grey") +
    coord_quickmap() +
    scale_x_continuous(expand = c(0, 0))+
    scale_y_continuous(expand = c(0, 0),limits = c(-42,35))+
    scale_size(limits = c(0,500))+
    geom_point(data=subset(carbon,BBC_mean!=0),
               aes(x=Longitude,y=Latitude,
                   shape=re_af,size=BBC_mean,color=Age),
               alpha=0.5) +
  mytheme+
    theme(
        panel.grid.major =element_blank(), 
        panel.grid.minor = element_blank(),
        axis.title.x = element_text(color="white"),
        legend.title=element_blank(),
        legend.background = element_blank(),
        legend.position ="bottom")+
    scale_colour_gradient(high = "#09386C", low = "#4B97EC")+   
    xlab("Longitude")+
    ylab("Latitude")


p3 =ggplot(data=subset(carbon,BBC_mean!=0),
           aes(x=Latitude,y=BBC_mean))+
    geom_point(aes(x=Latitude,y=BBC_mean,
                   size=BBC_mean,shape=re_af,color=Age),alpha=0.5,size=2) +
    geom_smooth(color="#08298A",alpha=0.2,size=0.5)+
    guides(color = FALSE)+ 
    scale_x_continuous(expand = c(0, 0),limits = c(-42,35))+
    scale_y_continuous(expand = c(0, 0),limits = c(-5,80))+
  mytheme+
    theme(
        axis.title.y = element_blank(),
        axis.text.y = element_blank(),
        axis.title.x = element_text(color="white"),
        panel.grid.major =element_blank(), 
        panel.grid.minor = element_blank(),
        legend.title=element_blank(),
        legend.background = element_blank(),
        legend.position ="bottom")+
    scale_colour_gradient(high = "#09386C", low = "#4B97EC")+
  coord_flip()


p4 = ggplot(world, aes(long, lat)) +
    geom_map(map=world, aes(map_id=region), 
             fill="lightgrey", color="grey") +
    coord_quickmap() +
    scale_x_continuous(expand = c(0, 0))+
    scale_y_continuous(expand = c(0, 0),limits = c(-42,35))+
    scale_size(limits = c(0,500))+
    geom_point(data=subset(carbon,SCS_mean_100!=0),
               aes(x=Longitude,y=Latitude,
                   shape=re_af,size=SCS_mean_100,color=Age),
               alpha=0.5) +
  mytheme+
    theme(
        panel.grid.major =element_blank(), 
        panel.grid.minor = element_blank(),
        legend.title=element_blank(),
        legend.background = element_blank(),
        legend.position ="bottom")+
    scale_colour_gradient(high = "#B8860B", low = "#E6BF83") + 
    xlab("Longitude")+
    ylab("Latitude")


p5 =ggplot(data=subset(carbon,SCS_mean_100!=0),
           aes(x=Latitude,y=SCS_mean_100))+
    geom_point(aes(x=Latitude,y=SCS_mean_100,
                   size=SCS_mean_100,
                   shape=re_af,color=Age),alpha=0.5,size=2) +
    geom_smooth(color="#B8860B",alpha=0.2,size=0.5)+
    guides(color = FALSE)+ 
    scale_x_continuous(expand = c(0, 0),limits = c(-42,35))+
  mytheme+
    theme(
        axis.title.y = element_blank(),
        axis.text.y = element_blank(),
        panel.grid.major =element_blank(), 
        panel.grid.minor = element_blank(),
        legend.title=element_blank(),
        legend.background = element_blank(),
        legend.position ="bottom")+
    scale_colour_gradient(high = "#B8860B", low = "#E6BF83")+
    ylab(expression(paste("Carbon density (Mg C ha"^-1*")")))+
  scale_y_continuous(limits = c(0,500))+
  coord_flip()

stat_box_data = function(y) {
  return( 
    data.frame(
      y = 550,
      label = paste('italic(n) ==', length(y) 
                    )
    )
  )
}

carbon_melt=subset(melt(carbon,id.vars=c("Region","re_af"),
                 measure.vars=c("ABC_mean","BBC_mean","SCS_mean_100"),
                 variable.name = "carbon"),value!=0)

carbon_melt$Region=factor(carbon_melt$Region,levels=c("American Pacific Ocean",
                                                      "American Atlantic Ocean",
                                                      "Africa Indian Ocean",
                                                      "Asia Indian Ocean",
                                                      "Asia Pacific Ocean"))

p8=ggplot(carbon_melt,aes(x=Region,y=value,fill=carbon,color=carbon))+
   scale_fill_manual(labels=c("Aboveground biomass carbon",
                             "Belowground biomass carbon",
                             "Sediment carbon - 1m depth"),
                     values=c("#006400","#08298A","#B8860B"))+
   scale_color_manual(labels=c("Aboveground biomass carbon",
                             "Belowground biomass carbon",
                             "Sediment carbon - 1m depth"),
                      values=c("#006400","#08298A","#B8860B"))+
   geom_boxplot(outlier.size = -1,lwd=0.3, alpha = 0,show.legend = F,add.params = list(size = 0.5,alpha=0.5))+
   ggbeeswarm::geom_quasirandom(size=2, 
                                dodge.width = .75,alpha=.5)+
   guides(color = guide_legend(override.aes = list(size = c(5,5,5))))+
   stat_summary(
    fun.data = stat_box_data, 
    geom = "text",
    position = position_dodge(width = .75),show.legend = F,size=2,family="Helvetica")+
  mytheme+
   theme(
        axis.title.x=element_blank(), 
        legend.title=element_blank(),
        legend.position = "top",
        panel.grid.major =element_blank(), 
        panel.grid.minor = element_blank())+
  ylab(expression(paste("Carbon density (Mg C ha"^-1*")")))+
  scale_x_discrete(labels= c("(Ⅰ) American Pacific Ocean",
         "(Ⅱ) American Atlantic Ocean",
         "(Ⅲ) Africa Indian Ocean",
         "(Ⅳ) Asia Indian Ocean",
         "(Ⅴ) Asia Pacific Ocean"))
  

ggarrange(p8,labels = c("a"),
          ggarrange(p,p1,p2,p3,p4,p5,ncol=2,nrow=3,
                    widths = c(3,1),
                    labels=c("b","","c","","d",""),align = "v",
                    font.label=list(face="plain",family = "Helvetica",size=7,face="bold"),
                    common.legend = T,legend = "bottom"),
          font.label=list(face="plain",family = "Helvetica",size=7,face="bold"),
          nrow = 2,
          heights = c(1.5,3.5))

ggsave(path = "[please change it into your own path]", 
       # Please change it into your own path
       filename="Fig.1.pdf",
       width = 178, height = 184, units = "mm")

```


```{r}
### Figure 2 ###
ABC=data %>% drop_na(ABC_mean)%>%filter(group=="restored")%>%filter(Age<=40)%>% 
  filter(Species!="")%>%
  filter(ABC_mean>0)%>%
  convert_as_factor(re_af,Species_2,plant_nature,climate.type_2)%>%mutate_all(type.convert)

BBC=data%>% drop_na(BBC_mean)%>%filter(group=="restored")%>%filter(Age<=40)%>%
  filter(Species!="")%>%
  filter(BBC_mean!="")%>%filter(BBC_mean>0)%>%
  convert_as_factor(re_af,Species_2,plant_nature,climate.type_2)%>%mutate_all(type.convert)

SCS=data%>% drop_na(SCS_mean_100)%>%filter(group=="restored")%>%filter(Age<=40)%>%
  filter(Species!="")%>%
  filter(SCS_mean_100>0)%>%
  convert_as_factor(re_af,Species_2,plant_nature,climate.type_2)%>%mutate_all(type.convert)

TECS=data%>% drop_na(TECS_mean)%>%filter(group=="restored")%>%filter(Age<=40)%>%
  filter(Species!="")%>%
  filter(TECS_mean>0)%>%
  convert_as_factor(re_af,Species_2,plant_nature,climate.type_2)%>%mutate_all(type.convert)


timeslice=function(data,time){
  l=nrow(data)
  timegroup=matrix(NA,nrow=l)
   for (i in c(1:l)){
    if (time[i]<=5){
      timegroup[i]="(0,5]"
    }else if(time[i]<=10){
      timegroup[i]="(5,10]"
    }else if(time[i]<=15){
      timegroup[i]="(10,15]"
    }else if(time[i]<=20){
      timegroup[i]="(15,20]"
    }else if(time[i]<=40){
      timegroup[i]="(20,40]"
    }
    else if(time[i]<=80){
        timegroup[i]="(40,80]"
    }
     }
  data=data.frame(data,timegroup=timegroup)
  return(data)
}  


ABC_select=timeslice(ABC,ABC$Age)
BBC_select=timeslice(BBC,BBC$Age)
SCS_select=timeslice(SCS,SCS$Age)
TECS_select=timeslice(TECS,TECS$Age)


ABC_select$timegroup=factor(ABC_select$timegroup,levels =
                              c("(0,5]","(5,10]","(10,15]","(15,20]","(20,40]","(40,80]"))
BBC_select$timegroup=factor(BBC_select$timegroup,levels = 
                              c("(0,5]","(5,10]","(10,15]","(15,20]","(20,40]","(40,80]"))
SCS_select$timegroup=factor(SCS_select$timegroup,levels =
                              c("(0,5]","(5,10]","(10,15]","(15,20]","(20,40]","(40,80]"))
TECS_select$timegroup=factor(TECS_select$timegroup,levels =
                               c("(0,5]","(5,10]","(10,15]","(15,20]","(20,40]","(40,80]"))


ABC_select=ABC_select%>%
  filter(timegroup!="(40,80]")
BBC_select=BBC_select%>%
  filter(timegroup!="(40,80]")
SCS_select=SCS_select%>%
  filter(timegroup!="(40,80]")
TECS_select=TECS_select%>%
  filter(timegroup!="(40,80]")


ABC_select_mean = ABC_select %>% 
  dplyr::group_by(timegroup,re_af) %>% 
  dplyr::summarize(average = mean(ABC_mean),
                   std=sd(ABC_mean,na.rm = TRUE)/sqrt(length(ABC_mean)),
                   median=median(ABC_mean)) %>%
  ungroup()

BBC_select_mean = BBC_select %>% 
  dplyr::group_by(timegroup,re_af) %>% 
  dplyr::summarize(average = mean(BBC_mean,na.rm=TRUE),
                   std=sd(BBC_mean,na.rm = TRUE)/sqrt(length(BBC_mean)),
                   median=median(BBC_mean)) %>%
  ungroup()

SCS_select_mean = SCS_select %>% 
  dplyr::group_by(timegroup,re_af) %>% 
  dplyr::summarize(average = mean(SCS_mean_100,na.rm=TRUE),
                   std=sd(SCS_mean_100,na.rm = TRUE)/sqrt(length(SCS_mean_100)),
                   median=median(SCS_mean_100)) %>%
  ungroup()

TECS_select_mean = TECS_select %>% 
  dplyr::group_by(timegroup,re_af) %>% 
  dplyr::summarize(average = mean(TECS_mean,na.rm=TRUE),
                   std=sd(TECS_mean,na.rm = TRUE)/sqrt(length(TECS_mean)),
                   median=median(TECS_mean)) %>%
  ungroup()

meansd=rbind(ABC_select_mean,BBC_select_mean,SCS_select_mean,TECS_select_mean)
write.csv(meansd,"mean_sd_group.csv")

### test of normality and homogeneity of model residuals
ano=aov(ABC_mean~re_af,data=ABC_select)
plot(ano,1)
leveneTest(ABC_mean~re_af,data=ABC_select)

# normality of residuals
plot(ano, 2)
aov_residuals <- residuals(object = ano)
shapiro.test(x = aov_residuals)

## Plot
mytheme=theme_bw()+
  theme(axis.text = element_text(family = "Helvetica",size=7),
  axis.text.x=element_text(face="plain",family = "Helvetica",size=7), 
        axis.text.y=element_text(face="plain",family = "Helvetica",size=7), 
        axis.title.y=element_text(face="plain",family = "Helvetica",size=7), 
        axis.title.x=element_blank(), 
        plot.title=element_text(hjust=0.5,vjust=0,family = "Helvetica",size=7),
        legend.text = element_text(family = "Helvetica",size=7),
        legend.title = element_blank(),
        panel.border = element_rect(fill=NA, size=0.4),
        legend.position = "bottom",
        strip.text.x = element_text(family = "Helvetica",size=7),
        panel.grid.major =element_blank(), 
        panel.grid.minor = element_blank(),
        axis.ticks = element_line(colour = 'black', size = 0.3))

# function for number of observations 
give.n <- function(x){
  return(data.frame(y = -1, label =  paste('italic(n) ==', length(x))))
  # experiment with the multiplier to find the perfect position
}

P1=ggplot(ABC_select,aes(x=timegroup,y=ABC_mean,color=re_af))+
  geom_boxplot(outlier.alpha = 0.2,outlier.size = 0.5,lwd=0.3)+
  stat_summary(fun.data = give.n, geom = "text", fun.y = median, size=2,
                   position = position_dodge(width = 0.75),parse=TRUE)+
  stat_compare_means(size=2,aes(label = ifelse(p <= 0.001,
                                               paste("italic(P)<=","0.001"),
                                               paste("italic(P)==",round(as.numeric(..p.format..),3)))),
                     label.y = 305,hide.ns = TRUE,show.legend = F,parse=TRUE)+
  scale_color_manual(values = c("reforestation"="#326232","afforestation"="#45DA54"))+
  stat_summary(fun.y=mean, geom="point", shape=1, size=1, aes(color=re_af),
             position = position_dodge2(width = 0.75,
                                        preserve = "single"))+
  geom_line(data = ABC_select_mean, 
            mapping = aes(x = timegroup, y = average,group=re_af),size=0.7,
            position = position_dodge())+
  scale_y_continuous(limits = c(-2,310))+
  mytheme+
    ggtitle(expression("Aboveground biomass carbon"))+
    xlab("Age Group (year)")+
    ylab(expression(paste("Carbon density (Mg C ha"^-1*")")))  


P2=ggplot(BBC_select,aes(x=timegroup,y=BBC_mean,color=re_af))+
  geom_boxplot(outlier.alpha = 0.2,outlier.size = 0.5,lwd=0.3)+
  stat_summary(fun.data = give.n, geom = "text", fun.y = median, size=2,
                   position = position_dodge(width = 0.75),parse=TRUE)+
  stat_compare_means(size=2,aes(label = ifelse(p <= 0.001,
                                               paste("italic(P)<=","0.001"),
                                               paste("italic(P)==",round(as.numeric(..p.format..),3)))),
                     label.y = 100,hide.ns = TRUE,show.legend = F,parse=TRUE)+
  scale_color_manual(values = c("reforestation"="#09386C","afforestation"="#70ABEB"))+
  stat_summary(fun.y=mean, geom="point", shape=1, size=1, aes(color=re_af),
             position = position_dodge2(width = 0.75,
                                        preserve = "single"))+
  geom_line(data = BBC_select_mean, 
            mapping = aes(x = timegroup, y = average,group=re_af),size=0.7,position = position_dodge())+
  mytheme+
    ggtitle(expression("Belowground biomass carbon"))+
    xlab("Age Group (year)")+
    ylab(expression(paste("Carbon density (Mg C ha"^-1*")")))  


P3=ggplot(SCS_select,aes(x=timegroup,y=SCS_mean_100,color=re_af))+
  geom_boxplot(outlier.alpha = 0.2,outlier.size = 0.5,lwd=0.3)+
  stat_summary(fun.data = give.n, geom = "text", fun.y = median, size=2,
                   position = position_dodge(width = 0.75),parse=TRUE)+
  stat_compare_means(size=2,aes(label = ifelse(p <= 0.001,
                                               paste("italic(P)<=","0.001"),
                                               paste("italic(P)==",round(as.numeric(..p.format..),3)))),
                     label.y = 480,hide.ns = TRUE,show.legend = F,parse=TRUE)+
  scale_color_manual(values = c("reforestation"="#B8860B","afforestation"="#F3D33A"))+
    stat_summary(fun.y=mean, geom="point", shape=1, size=1, aes(color=re_af),
             position = position_dodge2(width = 0.75,
                                        preserve = "single"))+
    geom_line(data = SCS_select_mean, 
            mapping = aes(x = timegroup, y = average,group=re_af),size=0.7,position = position_dodge())+
    mytheme+
    theme(axis.title.x=element_text(face="plain",family = "Helvetica",size=7))+
    ggtitle(expression("Sediment carbon - 1m depth"))+
    xlab("Age Group (year)")+
    ylab(expression(paste("Carbon density (Mg C ha"^-1*")")))  


P4=ggplot(TECS_select,aes(x=timegroup,y=TECS_mean,color=re_af))+
  geom_boxplot(outlier.alpha = 0.2,outlier.size = 0.5,lwd=0.3)+
  stat_summary(fun.data = give.n, geom = "text", fun.y = median, size=2,
                   position = position_dodge(width = 0.75),parse=TRUE)+
  stat_compare_means(size=2,aes(label = ifelse(p <= 0.001,
                                               paste("italic(P)<=","0.001"),
                                               paste("italic(P)==",round(as.numeric(..p.format..),3)))),
                     label.y = 510,hide.ns = TRUE,show.legend = F,parse=TRUE)+
  scale_color_manual(values = c("reforestation"="#AD3818","afforestation"="#FCB29E"))+
  stat_summary(fun.y=mean, geom="point", shape=1, size=1, aes(color=re_af),
             position = position_dodge2(width = 0.75,
                                        preserve = "single"))+
  geom_line(data = TECS_select_mean, 
            mapping = aes(x = timegroup, y = average,group=re_af),size=0.7,position = position_dodge())+
  mytheme+
    theme(axis.title.x=element_text(face="plain",family = "Helvetica",size=7))+
    ggtitle(expression("Total ecosystem carbon"))+
    xlab("Age Group (year)")+
    ylab(expression(paste("Carbon density (Mg C ha"^-1*")")))  


ggarrange(P1,P2,P3,P4, ncol = 2, nrow =2 ,labels="auto",heights=c(1,1.05),font.label=list(face="plain",family = "Helvetica",size=7,face="bold"),
             legend ="bottom",common.legend = T)

ggsave(path = "[please change it into your own path]",
       # change it into your own path
       filename="Fig.2.png",
       width = 180, height = 120, units = "mm",dpi=300)

```


```{r}
### Table S1 ###
fm=lmer(ABC_mean~Age*re_af+(1|ID),data=ABC)

summary(fm)
Anova(fm,type = 3)

fm_1=lmer(ABC_mean~log(Age)*re_af+(1|ID),data=ABC)

summary(fm_1)
Anova(fm_1,type = 3)

AIC(fm,fm_1)

fm2=lmer(BBC_mean~Age*re_af+(1|ID),data=BBC)

summary(fm2)
Anova(fm2,type = 3)

fm2_1=lmer(BBC_mean~log(Age)*re_af+(1|ID),data=BBC)

summary(fm2_1)
Anova(fm2_1,type = 3)

AIC(fm2,fm2_1)


fm3=lmer(SCS_mean_100~Age*re_af+(1|ID),data=SCS)

summary(fm3)
Anova(fm3,type = 3)

fm3_1=lmer(SCS_mean_100~log(Age)*re_af+(1|ID),data=SCS)

summary(fm3_1)
Anova(fm3_1,type = 3)

AIC(fm3,fm3_1)


fm4=lmer(TECS_mean~Age*re_af+(1|ID),data=TECS)

summary(fm4)
Anova(fm4,type = 3)

fm4_1=lmer(TECS_mean~log(Age)*re_af+(1|ID),data=TECS)

summary(fm4_1)
Anova(fm4_1,type = 3)

AIC(fm4,fm4_1)

```

```{r}
### Fig. S9 ##
ABC_re=ABC_select%>%filter(re_af=="reforestation")%>%
  filter(LULCC_before!="former mangrove site")%>%filter(Age>15)
BBC_re=BBC_select%>%filter(re_af=="reforestation")%>%
  filter(LULCC_before!="former mangrove site")%>%filter(Age>15)
SCS_re=SCS_select%>%filter(re_af=="reforestation")%>%
  filter(LULCC_before!="former mangrove site")%>%filter(Age>15)
TECS_re=TECS_select%>%filter(re_af=="reforestation")%>%
  filter(LULCC_before!="former mangrove site")%>%filter(Age>15)


ABC_re$LULCC_before=factor(ABC_re$LULCC_before,
                           levels=c("abandoned agricultural/aquacultural site",
                                    "clearing_cut site","site with mangrove mortality"))
BBC_re$LULCC_before=factor(BBC_re$LULCC_before,
                           levels=c("abandoned agricultural/aquacultural site",
                                    "clearing_cut site","site with mangrove mortality"))
SCS_re$LULCC_before=factor(SCS_re$LULCC_before,
                           levels=c("abandoned agricultural/aquacultural site",
                                    "clearing_cut site","site with mangrove mortality"))


# function for number of observations 
give.n <- function(x){
  return(data.frame(y = -1, label =  paste('italic(n) ==', length(x))))
  # experiment with the multiplier to find the perfect position
}

### test of normality and homogeneity of model residuals
ano=aov(ABC_mean~LULCC_before,data=ABC_re)
plot(ano,1)
leveneTest(ABC_mean~LULCC_before,data=ABC_re)

# normality of residuals
plot(ano, 2)
aov_residuals <- residuals(object = ano)
shapiro.test(x = aov_residuals)
## significant in the test of normality of model residuals


## use Kruskal–Wallis test with Dunn test as the post hoc test.
ano=kruskal.test(ABC_mean~LULCC_before,data=ABC_re)
DT=dunnTest(ABC_mean~LULCC_before,data=ABC_re,method="bonferroni")
PT=DT$res
a=cldList(P.adj ~ Comparison,
        data = PT,
        threshold = 0.05)
ABC_re_mean = ABC_re %>% 
  dplyr::group_by(LULCC_before) %>% 
  dplyr::summarize(average = mean(ABC_mean),
                   std=sd(ABC_mean,na.rm = TRUE)/sqrt(length(ABC_mean)),
                   median=median(ABC_mean)) %>%
  arrange(desc(average))%>%
  ungroup()
ABC_re_mean$cl=a$Letter

P1=ggboxplot(ABC_re,x="LULCC_before",y="ABC_mean",
          color = "LULCC_before", 
          add = "jitter",
          legend = "none",
          lwd=0.3,
          add.params = list(size = 0.6,alpha=0.5))+
  mytheme+
  theme(axis.text.x=element_text(hjust = 0.5,colour="white",size=3),
        axis.title.x = element_text(hjust = 0.5,colour="white",size=3),
        legend.title = element_blank())+
  geom_text(data = ABC_re_mean, aes(x = LULCC_before, y = 300, label = cl,color=LULCC_before), 
            size = 2.5,show.legend = F)+
  stat_summary(fun.data = give.n, geom = "text", fun.y = median, size=2,aes(color=LULCC_before),
                   position = position_dodge(width = 0.75),show.legend = F,parse=TRUE)+
    ylab(expression(paste("Aboveground biomass carbon density (Mg C ha"^-1*")")))+
  scale_color_discrete(labels=c("clearing_cut site"="clearing-cut site"))


### test of normality and homogeneity of model residuals
ano=aov(BBC_mean~LULCC_before,data=BBC_re)
plot(ano,1)
leveneTest(BBC_mean~LULCC_before,data=BBC_re)

# normality of residuals
plot(ano, 2)
aov_residuals <- residuals(object = ano)
shapiro.test(x = aov_residuals)

out=LSD.test(ano,"LULCC_before", p.adj="bonferroni")
plot(out)

## use Kruskal–Wallis test with Dunn test as the post hoc test.
ano=kruskal.test(BBC_mean~LULCC_before,data=BBC_re)
DT=dunnTest(BBC_mean~LULCC_before,data=BBC_re,method="bonferroni")
PT=DT$res
a=cldList(P.adj ~ Comparison,
        data = PT,
        threshold = 0.05)

BBC_re_mean = BBC_re %>% 
  dplyr::group_by(LULCC_before) %>% 
  dplyr::summarize(average = mean(BBC_mean),
                   std=sd(BBC_mean,na.rm = TRUE)/sqrt(length(BBC_mean)),
                   median=median(BBC_mean)) %>%
  arrange(desc(average))%>%
  ungroup()
BBC_re_mean$cl=a$Letter


P2=ggboxplot(BBC_re,x="LULCC_before",y="BBC_mean",
          color = "LULCC_before", 
          add = "jitter",
          legend = "none",
          lwd=0.3,
          add.params = list(size = 0.6,alpha=0.5))+
  mytheme+
  theme(axis.text.x=element_text(hjust = 0.5,colour="white",size=3),
        axis.title.x = element_text(hjust = 0.5,colour="white",size=3),
        legend.title = element_blank())+
  geom_text(data = BBC_re_mean, aes(x = LULCC_before, y = 100, label = cl,color=LULCC_before), 
            size = 2.5,show.legend = F)+
  stat_summary(fun.data = give.n, geom = "text", fun.y = median, size=2,aes(color=LULCC_before),
                   position = position_dodge(width = 0.75),show.legend = F,parse=TRUE)+
    ylab(expression(paste("Belowground biomass carbon density (Mg C ha"^-1*")")))+
  scale_color_discrete(labels=c("clearing_cut site"="clearing-cut site")) 

### test of normality and homogeneity of model residuals
ano=aov(SCS_mean_100~LULCC_before,data=SCS_re)
plot(ano,1)
leveneTest(SCS_mean_100~LULCC_before,data=SCS_re)

# normality of residuals
plot(ano, 2)
aov_residuals <- residuals(object = ano)
shapiro.test(x = aov_residuals)

out=LSD.test(ano,"LULCC_before", p.adj="bonferroni")
plot(out)

## use Kruskal–Wallis test with Dunn test as the post hoc test.
ano=kruskal.test(SCS_mean_100~LULCC_before,data=SCS_re)
DT=dunnTest(SCS_mean_100~LULCC_before,data=SCS_re,method="bonferroni")
PT=DT$res
a=cldList(P.adj ~ Comparison,
        data = PT,
        threshold = 0.05)

SCS_re_mean = SCS_re %>% 
  dplyr::group_by(LULCC_before) %>% 
  dplyr::summarize(average = mean(SCS_mean_100),
                   std=sd(SCS_mean_100,na.rm = TRUE)/sqrt(length(SCS_mean_100)),
                   median=median(SCS_mean_100)) %>%
  arrange(desc(average))%>%
  ungroup()
SCS_re_mean$cl=a$Letter

P3=ggboxplot(SCS_re,x="LULCC_before",y="SCS_mean_100",
          color = "LULCC_before", 
          add = "jitter",
          legend = "none",
          lwd=0.3,
          add.params = list(size = 0.6,alpha=0.5))+
  mytheme+
  theme(axis.text.x=element_text(hjust = 0.5,colour="white",size=3),
        axis.title.x = element_text(hjust = 0.5,colour="white",size=3),
        legend.title = element_blank())+
  geom_text(data = SCS_re_mean, aes(x = LULCC_before, y = 500, label = cl,color=LULCC_before), size = 2.5,
            show.legend = F)+
  stat_summary(fun.data = give.n, geom = "text", fun.y = median, size=2,aes(color=LULCC_before),
                   position = position_dodge(width = 0.75),show.legend = F,parse=TRUE)+
    ylab(expression(paste("Sediment carbon density-1 m depth (Mg C ha"^-1*")")))+
  scale_color_discrete(labels=c("clearing_cut site"="clearing-cut site")) 


ggarrange(P1,P2,P3,nrow=1,
          labels="auto",
          font.label=list(face="plain",family = "Helvetica",size=7,face="bold"),
          legend ="bottom",common.legend = T)


ggsave(path = "[please change it into your own path]",
       # change it into your own path
       filename="Fig.S9.png",
       width = 180, height = 80, units = "mm",dpi=300)

```

```{r}
### Fig. S3 ###
ABC_select=ABC_select%>%filter(re_af=="reforestation")

ABC_select$rate=ABC_select$ABC_mean/ABC_select$Age

ABC_select_mean = ABC_select %>% 
  dplyr::group_by(timegroup) %>% 
  dplyr::summarize(average = mean(rate),
                   std=sd(rate,na.rm = TRUE)/sqrt(length(rate)),
                   median=median(rate)) %>%
  arrange(desc(average))%>%
  ungroup()

### test of normality and homogeneity of model residuals
ano=aov(rate~timegroup,data=ABC_select)
plot(ano,1)
leveneTest(rate~timegroup,data=ABC_select)

# normality of residuals
plot(ano, 2)
aov_residuals <- residuals(object = ano)
shapiro.test(x = aov_residuals)
## significant in the test of normality and homoscedasticity of model residuals


## use Kruskal–Wallis test with Dunn test as the post hoc test.
ano=kruskal.test(rate~timegroup,data=ABC_select)
DT=dunnTest(rate~timegroup,data=ABC_select,method="bonferroni")
PT=DT$res
a=cldList(P.adj ~ Comparison,
        data = PT,
        threshold = 0.05)

ABC_select_mean$cl=a$Letter

# function for number of observations 
give.n <- function(x){
  return(data.frame(y = -1, label =  paste('italic(n) ==', length(x))))
  # experiment with the multiplier to find the perfect position
}

ggplot(ABC_select,aes(x=timegroup,y=rate))+
  geom_boxplot(outlier.alpha = 0.2,outlier.size = 0.5,lwd=0.3,color="#326232")+
  # geom_point(position=position_jitterdodge())+
  stat_summary(fun.data = give.n, geom = "text", fun.y = median, size=2.5,
                   position = position_dodge(width = 0.75),color="#326232",parse=TRUE)+
  geom_point(data=ABC_select_mean, 
           aes(x = timegroup, y = average,group=1),size=1,             
            position = position_dodge2(width = 0.75,
                                        preserve = "single"),color="#326232",shape=1)+
  geom_path(data = ABC_select_mean, 
           aes(x = timegroup, y = average,group=1),size=0.7,             
            position = position_dodge2(width = 0.75,
                                        preserve = "single"),color="#326232")+
  geom_text(data = ABC_select_mean, aes(x = timegroup, y = 12, label = cl), size = 2.5,color="#326232")+
  scale_y_continuous(limits = c(-2,12.5))+
  mytheme+
  theme(axis.title.x = element_text(face="plain",family = "Helvetica",size=7))+
    # ggtitle(expression("Aboveground biomass carbon"))+
    xlab("Age Group (year)")+
    ylab(expression(atop("Aboveground biomass carbon accumulation rate",
                                             atop(textstyle(("Mg C ha"^-1*" yr"^-1))))))

ggsave(path = "[Please change it to your own path]",
       # change it into your own path
       filename="Fig.S3.png",
       width = 100, height = 60, units = "mm",dpi=300)
```

```{r}
## Table S2 ##
fm=lmer(ABC_mean~Age+re_af+MAT+MAP+Age*re_af+Age*MAT+Age*MAP+Age*re_af*MAP+Age*re_af*MAT+(1|ID),data=ABC)
fm_log=lmer(ABC_mean~log(Age)+re_af+MAT+MAP+log(Age)*re_af+log(Age)*MAT+log(Age)*MAP+log(Age)*re_af*MAP+log(Age)*re_af*MAT+(1|ID),data=ABC)
AIC(fm,fm_log)
summary(fm_log)
Anova(fm_log)


fm=lmer(BBC_mean~Age+re_af+MAT+MAP+Age*re_af+Age*MAT+Age*MAP+Age*re_af*MAP+Age*re_af*MAT+(1|ID),data=BBC)
fm_log=lmer(BBC_mean~log(Age)+re_af+MAT+MAP+log(Age)*re_af+log(Age)*MAT+log(Age)*MAP+log(Age)*re_af*MAP+log(Age)*re_af*MAT+(1|ID),data=BBC)
AIC(fm,fm_log)
summary(fm_log)
Anova(fm_log)

```

```{r}
## Fig. S4##
MAP_slice=function(data,MAP){
  l=nrow(data)
  MAPgroup=matrix(NA,nrow=l)
   for (i in c(1:l)){
    if (MAP[i]<=500){
      MAPgroup[i]="(0,500]"
    }else if(MAP[i]<=1500){
      MAPgroup[i]="(500,1500]"
    }else if(MAP[i]<=2500){
      MAPgroup[i]="(1500,2500]"
    }else if(MAP[i]<=3500){
      MAPgroup[i]="(2500,3500]"
    }else if(MAP[i]<=5000){
      MAPgroup[i]="(3500,5000]"
    }
     }
  data=data.frame(data,MAPgroup=MAPgroup)
  return(data)
}

# function for number of observations 
give.n <- function(x){
  return(data.frame(y = -8, label =paste(length(x))))
  # experiment with the multiplier to find the perfect position
}

ABC_time=timeslice(ABC,ABC$Age)
ABC_time$timegroup=factor(ABC_time$timegroup,levels =
                              c("(0,5]","(5,10]","(10,15]","(15,20]","(20,40]","(40,80]"))
ABC_time=ABC_time%>%filter(timegroup!="(40,80]")


ABC_timeMAP=MAP_slice(ABC_time,ABC_time$MAP)
ABC_timeMAP$MAPgroup=factor(ABC_timeMAP$MAPgroup,levels =
                              c("(0,500]","(500,1500]","(1500,2500]","(2500,3500]","(3500,5000]"))
ABC_timeMAP=ABC_timeMAP%>%filter(MAPgroup=="(500,1500]"|MAPgroup=="(1500,2500]"|MAPgroup=="(2500,3500]")

ABC_timeMAP$inter=factor(interaction(ABC_timeMAP$re_af,ABC_timeMAP$MAPgroup))

ABC_timeMAP_sum=ABC_timeMAP%>%group_by(inter,timegroup)%>%summarise(average=mean(ABC_mean))


P1=ggplot(ABC_timeMAP,aes(x=timegroup,y=ABC_mean,color=inter))+
  geom_boxplot(outlier.alpha=0.2,outlier.size = 0.5,lwd=0.3)+
  stat_summary(fun.data = give.n, geom = "text", fun.y = median, size=2,
                   position = position_dodge(width = 0.75),show.legend = F)+
  stat_compare_means(size=2.5,aes(label = ifelse(p <= 0.001,
                                               paste("italic(P)<=","0.001"),
                                               paste("italic(P)==",round(as.numeric(..p.format..),3)))),
                     label.y = 240,hide.ns = TRUE,show.legend = F, method = 'kruskal.test',parse=TRUE)+
  scale_color_manual(values = c("afforestation.(500,1500]"="#00D7FF",
                                "reforestation.(500,1500]"="#FFC4C4",
                                "afforestation.(1500,2500]"="#0096FF",
                                "reforestation.(1500,2500]"="#FF869E",
                                "afforestation.(2500,3500]"="#003865",
                                "reforestation.(2500,3500]"="#A10035"))+
  stat_summary(fun.y=mean, geom="point", shape=1, size=1, aes(color=inter),
             position = position_dodge2(width = 0.75,
                                        preserve = "total"))+
  guides(color=guide_legend(title=expression(paste(
    "Restoration pathways + Precipitation group (mm yr"^-1*")")), 
                            title.position = "top", 
                              title.hjust = 0.5))+
  geom_line(data = ABC_timeMAP_sum, 
            mapping = aes(x = timegroup, y = average,group=inter),
            size=0.5,position = position_dodge())+
  scale_y_continuous(limits = c(-10,250))+
  mytheme+
    theme(legend.title =element_text(face="plain",family = "Helvetica",size=7),
          axis.title.x =element_text(face="plain",family = "Helvetica",size=7) )+
    # ggtitle(expression("Aboveground biomass carbon"))+
    xlab("Age Group (year)")+
    ylab(expression(atop("Aboveground biomass carbon density", paste("(Mg C ha"^-1*")")))) 

give.n <- function(x){
  return(data.frame(y = -4, label =paste(length(x))))
  # experiment with the multiplier to find the perfect position
}

BBC_time=timeslice(BBC,BBC$Age)
BBC_time$timegroup=factor(BBC_time$timegroup,levels =
                              c("(0,5]","(5,10]","(10,15]","(15,20]","(20,40]","(40,80]"))
BBC_time=BBC_time%>%filter(timegroup!="(40,80]")


BBC_timeMAP=MAP_slice(BBC_time,BBC_time$MAP)
BBC_timeMAP$MAPgroup=factor(BBC_timeMAP$MAPgroup,levels =
                              c("(0,500]","(500,1500]","(1500,2500]","(2500,3500]","(3500,5000]"))
BBC_timeMAP=BBC_timeMAP%>%filter(MAPgroup=="(500,1500]"|MAPgroup=="(1500,2500]"|MAPgroup=="(2500,3500]")

BBC_timeMAP$inter=factor(interaction(BBC_timeMAP$re_af,BBC_timeMAP$MAPgroup))

BBC_timeMAP_sum=BBC_timeMAP%>%group_by(inter,timegroup)%>%summarise(average=mean(BBC_mean))


P2=ggplot(BBC_timeMAP,aes(x=timegroup,y=BBC_mean,color=inter))+
  geom_boxplot(outlier.alpha=0.2,outlier.size = 0.5,lwd=0.3)+
  stat_summary(fun.data = give.n, geom = "text", fun.y = median, size=2,
                   position = position_dodge(width = 0.75),show.legend = F)+
  stat_compare_means(size=2.5,aes(label = ifelse(p <= 0.001,
                                               paste("italic(P)<=","0.001"),
                                               paste("italic(P)==",round(as.numeric(..p.format..),3)))),
                     label.y =65,hide.ns = TRUE,show.legend = F,
                     method = 'kruskal.test',parse=TRUE)+
  scale_color_manual(values = c("afforestation.(500,1500]"="#00D7FF",
                                "reforestation.(500,1500]"="#FFC4C4",
                                "afforestation.(1500,2500]"="#0096FF",
                                "reforestation.(1500,2500]"="#FF869E",
                                "afforestation.(2500,3500]"="#003865",
                                "reforestation.(2500,3500]"="#A10035"))+
  stat_summary(fun.y=mean, geom="point", shape=1, size=1, aes(color=inter),
             position = position_dodge2(width = 0.75,
                                        preserve = "single"))+
  geom_line(data = BBC_timeMAP_sum, 
            mapping = aes(x = timegroup, y = average,group=inter),
            size=0.5,position = position_dodge())+
  guides(color=guide_legend(title=expression(paste(
    "Restoration pathways + Precipitation group (mm yr"^-1*")")), 
                            title.position = "top", 
                              title.hjust = 0.5))+
  scale_y_continuous(limits = c(-6,70))+
  mytheme+
    theme(legend.title =element_text(face="plain",family = "Helvetica",size=7),
          axis.title.x =element_text(face="plain",family = "Helvetica",size=7))+
    # ggtitle(expression("Belowground biomass carbon"))+
    xlab("Age Group (year)")+
    ylab(expression(atop("Belowground biomass carbon density", paste("(Mg C ha"^-1*")")))) 

data$re_af=factor(data$re_af,level=c("afforestation","reforestation"))
data_1=data%>%filter(group!="intact")

P3=ggdensity(data_1, x = "MAP",aes(y = ..count..),
   # add = "mean", 
   rug = FALSE,
   color = "re_af", fill = "re_af",
   palette = c("#0073C2FF", "#FC4E07"))+
  ylab(expression(atop(" ",paste("Relative Frequency"))))+
  xlab(expression(paste("Mean Annual Precipitation (mm yr"^-1*")")))+
  # theme(panel.border = element_rect(fill=NA))+
  mytheme+
  scale_y_continuous(expand = c(0,0))+
  # scale_x_continuous()+
  theme(legend.position = c(0.9, 0.9),
        legend.background = element_blank(),
        legend.title = element_blank(),
        axis.title.x = element_text(face="plain",family = "Helvetica",size=7))+
  geom_vline(aes(xintercept = 500), 
             linetype = "dashed", size = 0.4,
             color = "black")+
  geom_vline(aes(xintercept = 1500), 
             linetype = "dashed", size = 0.4,
             color = "black")+
  geom_vline(aes(xintercept = 2500), 
             linetype = "dashed", size = 0.4,
             color = "black")+
  geom_vline(aes(xintercept = 3500), 
             linetype = "dashed", size = 0.4,
             color = "black")

wilcox.test(data_1$MAP~data_1$re_af)

ggarrange(P3,
          ggarrange(P1,P2, ncol = 1, nrow =2,labels=c("b","c"),
                    font.label=list(face="plain",family = "Helvetica",size=7,face="bold"),
                    legend ="bottom",common.legend = T),
          ncol=1,
          # widths=c(1,1),
          heights=c(1,2.5),
          labels=c("a"),
          font.label=list(face="plain",family = "Helvetica",size=7,face="bold"),
          legend ="top",common.legend = F)


ggsave(path = "[please change it into your own path]",
       # change it into your own path
       filename="Fig.S4.png",
       width = 150, height = 200, units = "mm",dpi=300)
```

```{r}
### Fig. S2 ###
timeslice=function(data,time){
  l=nrow(data)
  timegroup=matrix(NA,nrow=l)
   for (i in c(1:l)){
    if (time[i]<=5){
      timegroup[i]="(0,5]"
    }else if(time[i]<=10){
      timegroup[i]="(5,10]"
    }else if(time[i]<=15){
      timegroup[i]="(10,15]"
    }else if(time[i]<=40){
      timegroup[i]="(15,40]"
    }
    else if(time[i]<=80){
        timegroup[i]="(40,80]"
    }
     }
  data=data.frame(data,timegroup=timegroup)
  return(data)
} 

SCS=data%>%filter(group=="restored")%>%filter(Age<=40)%>%
  filter(Species!="")%>%
  convert_as_factor(re_af,Species_2,plant_nature,climate.type_2)%>%mutate_all(type.convert)


SCS=timeslice(SCS,SCS$Age)
SCS$timegroup=factor(SCS$timegroup,levels =
                              c("(0,5]","(5,10]","(10,15]","(15,40]"))

SCS=SCS%>%filter(timegroup!="(40,80]")


SCS_select_mean = SCS %>% 
  dplyr::group_by(timegroup,re_af) %>% 
  dplyr::summarize(average_all=mean(SCS_increase_all,na.rm=TRUE),
                   sd=sd(SCS_increase_all,na.rm=TRUE)/sqrt(length(SCS_increase_all)),
                   median=median(SCS_increase_all)) %>%
  ungroup()

ggplot(SCS,aes(x=Age,y=SCS_increase_all,color=re_af))+
  geom_point()

give.n <- function(x){
  return(data.frame(y = -45, label =  paste('italic(n) ==', length(x))))
  # experiment with the multiplier to find the perfect position
}

ggplot(SCS,aes(x=timegroup,y=SCS_increase_all,color=re_af))+
  geom_boxplot(outlier.alpha=0.2,outlier.size = 0.5,lwd=0.3)+
  stat_summary(fun.data = give.n, geom = "text", fun.y = median, size=2,show.legend = F,
                   position = position_dodge(width = 0.75),parse=TRUE)+
  stat_compare_means(size=2,aes(label = ifelse(p <= 0.001,
                                               paste("italic(P)<=","0.001"),
                                               paste("italic(P)==",round(as.numeric(..p.format..),3)))),
                     label.y = 180,hide.ns = TRUE,show.legend = F,parse=TRUE)+
  scale_color_manual(values = c("reforestation"="#B8860B","afforestation"="#F3D33A"))+
    stat_summary(fun.y=mean, geom="point", shape=1, size=1, aes(color=re_af),
             position = position_dodge2(width = 0.75,
                                        preserve = "single"))+
    geom_line(data = SCS_select_mean, 
            mapping = aes(x = timegroup, y = average_all,group=re_af),size=0.7,position = position_dodge())+
    mytheme+
    theme(axis.title.x=element_text(face="plain",family = "Helvetica",size=7),
          legend.title = element_blank(),
          legend.margin=margin(t=-5))+
    ggtitle(expression("Sediment carbon - 1m depth"))+
    xlab("Age Group (year)")+
    ylab(expression(paste("Carbon density increment (Mg C ha"^-1*")"))) 


ggsave(path = "[please change it into your own path]",
       # change it into your own path
       filename="Fig.S2.png",
       width = 100, height = 70, units = "mm",dpi=300)
```



```{r}
### Figure 3 ###
data$re_af=factor(data$re_af,level=c("afforestation","reforestation"))
data_1=data%>%filter(group=="restored")%>%filter(ABC_mean!=""|BBC_mean!=""|SCS_mean_100!=""|TECS_mean!="")

data_1$SC_mean=as.numeric(data_1$SC_mean)

mytheme=theme_bw()+
  theme(axis.text = element_text(family = "Helvetica",size=5),
  axis.text.x=element_text(face="plain",family = "Helvetica",size=5), 
        axis.text.y=element_text(face="plain",family = "Helvetica",size=5), 
        axis.title.y=element_text(face="plain",family = "Helvetica",size=5), 
        axis.title.x=element_text(face="plain",family = "Helvetica",size=5), 
        plot.title=element_text(hjust=0.5,vjust=0,family = "Helvetica",size=5),
        legend.text = element_text(family = "Helvetica",size=5),
        legend.title = element_blank(),
        panel.border = element_rect(fill=NA, size=0.4),
        legend.position = "bottom",
        strip.text.x = element_text(family = "Helvetica",size=5),
        panel.grid.major =element_blank(), 
        panel.grid.minor = element_blank(),
        axis.ticks = element_line(colour = 'black', size = 0.3),
        axis.ticks.length=unit(0.5, "mm"),
        legend.margin=margin(0,0,0,0),
        legend.box.margin=margin(-5,0,-5,0))

# function for number of observations 
give.n <- function(x){
  return(data.frame(y = 3, label =  paste('italic(n) ==', length(x))))
  # experiment with the multiplier to find the perfect position
}

P1=ggplot(ABC,aes(x=salinity_pore,y=ABC_mean))+
   geom_point(aes(color=re_af),
              size=1,alpha=0.6)+
      geom_smooth(color="#006400",
                  fill="grey",
              formula=y ~ x,
              method=lm,
              alpha=0.2,
              size=0.5)+
      stat_poly_eq(formula = y~x,
               aes(label = paste(..rr.label..,..p.value.label..,sep = "~~~")),
               size=1.5,
               label.y = "top", label.x = "left",
               parse = TRUE)+
    scale_color_manual(values = c("reforestation"="#006400","afforestation"="#51C151"))+
  mytheme+
    xlab(expression(paste("Sediment porewater salinity (psu)")))+
    ylab(expression(paste("Carbon density (Mg C ha"^-1*")")))

P5=ggboxplot(data_1,x="re_af",y="salinity_pore",
          color = "re_af", 
          add = "jitter",
          legend = "none",
          lwd=0.3,
          add.params = list(size = 0.6,alpha=0.5))+
  mytheme+
  theme(axis.text.x=element_text(hjust = 0.5,colour="white",size=3),
        axis.title.x = element_text(hjust = 0.5,colour="white",size=3))+
    scale_color_manual(values = c("reforestation"="#006400","afforestation"="#51C151"))+
  stat_compare_means(size=1.5,aes(label = ifelse(p <= 0.001,
                                               paste("italic(P)<=","0.001"),
                                               paste("italic(P)==",round(as.numeric(..p.format..),3)))),
                     label.x = 1.2,label.y = 78,hide.ns = TRUE,show.legend = F,parse=TRUE)+
  stat_summary(fun.data = give.n, geom = "text", fun.y = median, size=1.5,aes(color=re_af),
                   position = position_dodge(width = 0.75),parse=TRUE)+
  ylab(expression(paste("Sediment porewater salinity (psu)")))+
  scale_y_continuous(limits = c(0,80))

P2=ggplot(ABC,aes(x=SC_mean,y=ABC_mean))+
   geom_point(aes(color=re_af),
              size=1,alpha=0.6)+
      geom_smooth(color="#006400",
                  fill="grey",
              formula=y ~ x,
              method=lm,
              alpha=0.2,
              size=0.5)+
      stat_poly_eq(formula = y~x,
               aes(label = paste(..rr.label..,..p.value.label..,sep = "~~~")),
               size=1.5,
               label.y = "top", label.x = "left",
               parse = TRUE)+
    scale_color_manual(values = c("reforestation"="#006400","afforestation"="#51C151"))+
  mytheme+
    xlab(expression(paste("Sediment total organic carbon content (%)")))+
    ylab(expression(paste("Carbon density (Mg C ha"^-1*")")))

# function for number of observations 
give.n <- function(x){
  return(data.frame(y = -1, label =  paste('italic(n) ==', length(x))))
  # experiment with the multiplier to find the perfect position
}

P6=ggboxplot(data_1,x="re_af",y="SC_mean",
          color = "re_af", 
          add = "jitter",
          legend = "none",
          lwd=0.3,
          add.params = list(size = 0.6, alpha=0.5))+
    scale_color_manual(values = c("reforestation"="#006400","afforestation"="#51C151"))+
  stat_compare_means(size=1.5,aes(label = ifelse(p <= 0.001,
                                               paste("italic(P)<=","0.001"),
                                               paste("italic(P)==",round(as.numeric(..p.format..),3)))),
                     label.x = 1.2,label.y = 20,
                     show.legend = F,hide.ns = TRUE,parse=TRUE)+
    stat_summary(fun.data = give.n, geom = "text", fun.y = median, size=1.5,aes(color=re_af),
                   position = position_dodge(width = 0.75),parse=TRUE)+
  mytheme+
  theme(axis.text.x=element_text(hjust = 0.5,colour="white",size=3),
        axis.title.x = element_text(hjust = 0.5,colour="white",size=3))+
      scale_y_continuous(limits=c(-2,22),breaks = seq(0,20,5),expand=c(0,0))+
    ylab(expression(paste("Sediment total organic carbon content (%)")))


P3=ggplot(ABC,aes(x=N.concentration_mean,y=ABC_mean))+
   geom_point(aes(color=re_af),
              size=1,alpha=0.6)+
      geom_smooth(color="#006400",
                  fill="grey",
              formula=y ~ x,
              method=lm,
              alpha=0.2,
              size=0.5)+
      stat_poly_eq(formula = y~x,
               aes(label = paste(..rr.label..,..p.value.label..,sep = "~~~")),
               size=1.5,
               label.y = "top", label.x = "left",
               parse = TRUE)+
    scale_color_manual(values = c("reforestation"="#006400","afforestation"="#51C151"))+
  mytheme+
    xlab(expression(paste("Sediment total nitrogen content (%)")))+
    ylab(expression(paste("Carbon density (Mg C ha"^-1*")")))

# function for number of observations 
give.n <- function(x){
  return(data.frame(y = 0, label =  paste('italic(n) ==', length(x))))
  # experiment with the multiplier to find the perfect position
}

P7=ggboxplot(data_1,x="re_af",y="N.concentration_mean",
          color = "re_af", 
          add = "jitter",
          legend = "none",
          lwd=0.3,
          add.params = list(size = 0.6, alpha = 0.5))+
    scale_color_manual(values = c("reforestation"="#006400","afforestation"="#51C151"))+
  stat_compare_means(size=1.5,aes(label = ifelse(p <= 0.001,
                                               paste("italic(P)<=","0.001"),
                                               paste("italic(P)==",round(as.numeric(..p.format..),3)))),
                     label.x = 1.2,label.y = 0.75,
                     show.legend = F,hide.ns = TRUE,parse=TRUE)+
    stat_summary(fun.data = give.n, geom = "text", fun.y = median, size=1.5,aes(color=re_af),
                   position = position_dodge(width = 0.75),parse=TRUE)+
  mytheme+
  theme(axis.text.x=element_text(hjust = 0.5,colour="white",size=3),
        axis.title.x = element_text(hjust = 0.5,colour="white",size=3))+
  scale_y_continuous(limits = c(0,0.8))+
  ylab(expression(paste("Sediment total nitrogen content (%)")))

P8=ggplot(ABC,aes(x=MAP,y=ABC_mean,color=re_af,fill=re_af))+
   geom_point(aes(color=re_af),size=1,
              alpha=0.6)+
      geom_smooth(
        # color="#006400",
        #           fill="grey",
              formula=y ~ x,
              method=lm,
              alpha=0.2,
              size=0.5)+
      stat_poly_eq(formula = y~x,
               aes(label = paste(..rr.label..,..p.value.label..,sep = "~~~")),
               size=1.5,
               label.y = "top", label.x = "left",
               parse = TRUE)+
    scale_color_manual(values = c("reforestation"="#006400","afforestation"="#51C151"))+
  scale_fill_manual(values = c("reforestation"="#006400","afforestation"="#51C151"))+
  # scale_x_continuous(limits = c(1000,3500))+
  mytheme+
  xlab(expression(paste("Mean annual precipitation (mm yr"^-1*")")))+
    ylab(expression(paste("Carbon density (Mg C ha"^-1*")")))

# function for number of observations 
give.n <- function(x){
  return(data.frame(y = -100, label =  paste('italic(n) ==', length(x))))
  # experiment with the multiplier to find the perfect position
}

P9=ggboxplot(data_1,x="re_af",y="MAP",
          color = "re_af", 
          add = "jitter",
          legend = "none",
          lwd=0.3,
          add.params = list(size = 0.6,alpha=0.5))+
  mytheme+
  theme(axis.text.x=element_text(hjust = 0.5,colour="white",size=3),
        axis.title.x = element_text(hjust = 0.5,colour="white",size=3))+
    scale_color_manual(values = c("reforestation"="#006400","afforestation"="#51C151"))+
  stat_compare_means(size=1.5,aes(label = ifelse(p <= 0.001,
                                               paste("italic(P)<=","0.001"),
                                               paste("italic(P)==",round(as.numeric(..p.format..),3)))),
                     label.x = 1.2,label.y = 4400,
                     show.legend = F,hide.ns = TRUE,parse=TRUE)+
    stat_summary(fun.data = give.n, geom = "text", fun.y = median, size=1.5,aes(color=re_af),
                   position = position_dodge(width = 0.75),parse=TRUE)+
  ylab(expression(paste("Mean annual precipitation (mm yr"^-1*")")))+
  scale_y_continuous(limits = c(-200,4600))


ggarrange(P8,P9,P2,P6,P3,P7,P1,P5, ncol = 2, nrow =4,widths = c(2,1) ,labels="auto",common.legend = TRUE,legend="bottom",align = "v",font.label=list(face="plain",family = "Helvetica",size=7,face="bold"))

ggsave(path = "[please change it into your own path]",
       filename="Fig.3.png",
       width = 75, height = 140, units = "mm",dpi=300)

```

```{r}
### Fig. S6 ###
RS=data_1

RS_melt_nutrient=melt(RS,
              id.vars = c("BA","re_af"),
             measure.vars = c("salinity_pore",
                              "silt",
                              "clay",
                              "sand",
                              "SC_mean",
                              "TN_mean",
                              "N.concentration_mean",
                              "C.N",
                              "initial_SC",
                              "initial_TN",
                              "initial_N",
                              "initial_CN",
                              "initial_salinity",
                              "initial_pH",
                              "initial_clay",
                              "initial_silt",
                              "initial_sand",
                              "pH"),
             variable.name = "initial")%>%
  mutate_all(type.convert)

mytheme=theme_bw()+
  theme(axis.text = element_text(family = "Helvetica",size=5),
  axis.text.x=element_text(face="plain",family = "Helvetica",size=5), 
        axis.text.y=element_text(face="plain",family = "Helvetica",size=5), 
        axis.title.y=element_text(face="plain",family = "Helvetica",size=5), 
        axis.title.x=element_text(face="plain",family = "Helvetica",size=5),  
        plot.title=element_text(hjust=0.5,vjust=0,family = "Helvetica",size=5),
        legend.text = element_text(family = "Helvetica",size=5),
        legend.title = element_blank(),
        panel.border = element_rect(fill=NA, size=0.4),
        legend.position = "bottom",
        strip.text.x = element_text(family = "Helvetica",size=5),
        panel.grid.major =element_blank(), 
        panel.grid.minor = element_blank(),
        axis.ticks = element_line(size = 0.3),
        legend.margin=margin(0,0,0,0),
        legend.box.margin=margin(-5,10,-5,10))


P2=ggplot(RS,aes(x=salinity_pore,y=BA))+
   geom_point(aes(color=re_af),
              size=2,alpha=0.6)+
      geom_smooth(color="#4B97EC",
              formula=y ~ x,
              method=lm,
              alpha=0.2,lwd=0.3)+
      stat_poly_eq(formula = y~x,
               aes(label = paste(..rr.label..,..p.value.label..,sep = "~~~")),
               size=2,
               label.y = "top", label.x = "left",
               parse = TRUE)+
  mytheme+
  scale_x_continuous(limits=c(15,70),expand=c(0,0))+
  scale_y_continuous(limits=c(0,2),expand=c(0,0))+
    xlab("Sediment porewater salinity (psu)")+
    ylab("BGC/AGC")

# function for number of observations 
give.n <- function(x){
  return(data.frame(y = 3, label =  paste('italic(n) ==', length(x))))
  # experiment with the multiplier to find the perfect position
}

P4=ggboxplot(data_1,x="re_af",y="salinity_pore",
          color = "re_af", 
          add = "jitter", 
          legend = "none",
          lwd=0.3,
          add.params = list(size = 0.6, alpha = 0.5))+
  stat_compare_means(size=2,aes(label = ifelse(p <= 0.001,
                                               paste("italic(P)<=","0.001"),
                                               paste("italic(P)==",round(as.numeric(..p.format..),3)))),
                     label.x = 1.2,label.y = 70,
                     show.legend = F,hide.ns = TRUE,parse=TRUE)+
  stat_summary(fun.data = give.n, geom = "text", fun.y = median, size=1.5,aes(color=re_af),
                   position = position_dodge(width = 0.75),parse=TRUE)+
  mytheme+
  theme(axis.title.x = element_text(hjust = 0.5,colour="white",size=5),
        axis.text.x = element_text(face="plain",color="white",size=5))+
  ylab(expression(paste("Sediment porewater salinity (psu)")))


ggarrange(P2,P4,ncol = 2,nrow=1,widths = c(2,1),labels="auto",legend = "bottom",common.legend = T,font.label=list(face="plain",family = "Helvetica",size=7,face="bold"))


ggsave(path = "[Please change it to your own path]",
       filename="Fig.S6.png",
       width = 88, height = 50, units = "mm")

```

```{r}
#### Fig. 4 + Table S7 ####
data=read.csv("Supplementary Data1221.csv",stringsAsFactors = FALSE,fileEncoding="latin1")

data=data%>%
  filter(ID<1000)%>%  # delete abnormal data
  filter(re_af!="")%>%
  filter(Age<=40)

colnames(data)[c(19:24,26,28:33,35)]=c("BC_mean","ABC_mean","BBC_mean",
                                    "SCS_mean","SCS_mean_100","SCS_increase_all",
                                       "SC_mean","TECS_mean",
                                       "salinity_pore",
                                       "sand","silt","clay",
                                       "TN_mean","N.concentration_mean")  ## simplify column names


ABC=data %>% drop_na(ABC_mean)%>%filter(group=="restored")%>% 
  filter(Species!="")%>%
  filter(ABC_mean>0)%>%
  convert_as_factor(re_af,Species_2,plant_nature,climate.type_2)%>%mutate_all(type.convert)

BBC=data%>% drop_na(BBC_mean)%>%filter(group=="restored")%>%
  filter(Species!="")%>%
  filter(BBC_mean!="")%>%filter(BBC_mean>0)%>%
  convert_as_factor(re_af,Species_2,plant_nature,climate.type_2)%>%mutate_all(type.convert)

SCS=data%>% drop_na(SCS_mean_100)%>%filter((group=="restored"&Species!="")|(group=="initial"))%>%
  # filter(Species!="")%>%
  filter(SCS_mean_100>0)%>%
  convert_as_factor(re_af,Species_2,plant_nature,climate.type_2)%>%mutate_all(type.convert)

TECS=data%>% drop_na(TECS_mean)%>%filter((group=="restored"&Species!="")|(group=="initial"))%>%
  # filter(Species!="")%>%
  filter(TECS_mean>0)%>%
  convert_as_factor(re_af,Species_2,plant_nature,climate.type_2)%>%mutate_all(type.convert)


ABC_ref=ABC%>%filter(re_af=="reforestation")%>%arrange(Age)
ABC_aff=ABC%>%filter(re_af=="afforestation")%>%arrange(Age)

Gompertz = function(x, Asym, b2, b3) Asym*exp(-b2*b3^x)
fit_ref_ABC = nls(ABC_mean~Gompertz(Age,Asym,b2,b3),data=ABC_ref,start=list(Asym=115.72,b2=1.4,b3=0.95))
fit_aff_ABC = nls(ABC_mean~Gompertz(Age,Asym,b2,b3),data=ABC_aff,start=list(Asym=91.55,b2=1.4,b3=0.9))

BBC_ref=BBC%>%filter(re_af=="reforestation")%>%arrange(Age)
BBC_aff=BBC%>%filter(re_af=="afforestation")%>%arrange(Age)

fit_ref_BBC = nls(BBC_mean~Gompertz(Age,Asym,b2,b3),data=BBC_ref,start=list(Asym=95.56,b2=2.74,b3=0.96))
fit_aff_BBC = nls(BBC_mean~Gompertz(Age,Asym,b2,b3),data=BBC_aff,start=list(Asym=75,b2=2,b3=0.96))

SCS_ref=SCS%>%filter(re_af=="reforestation")%>%arrange(Age)
SCS_aff=SCS%>%filter(re_af=="afforestation")%>%arrange(Age)

Gompertz = function(x, Asym, b2, b3) Asym*exp(-b2*b3^x)
fit_ref_SCS = nls(SCS_mean_100~Gompertz(Age,Asym,b2,b3),data=SCS_ref,start=list(Asym=510,b2=0.3,b3=0.9))
fit_aff_SCS = nls(SCS_mean_100~Gompertz(Age,Asym,b2,b3),data=SCS_aff,start=list(Asym=240,b2=0.67,b3=0.9))

TECS_ref=TECS%>%filter(re_af=="reforestation")%>%arrange(Age)
TECS_aff=TECS%>%filter(re_af=="afforestation")%>%arrange(Age)

Gompertz = function(x, Asym, b2, b3) Asym*exp(-b2*b3^x)
# fit_ref_TECS = nls(TECS_mean~Gompertz(Age,Asym,b2,b3),data=TECS_ref,start=list(Asym=450,b2=1.2,b3=0.9))
fit_ref_TECS = nls(TECS_mean~Gompertz(Age,Asym,b2,b3),data=TECS_ref,start=list(Asym=450,b2=0.8,b3=0.9))
fit_aff_TECS = nls(TECS_mean~Gompertz(Age,Asym,b2,b3),data=TECS_aff,start=list(Asym=200,b2=1.4,b3=0.9))

am=function(fit,name){
  a=summary(fit)$sigma
  b=coef(fit)
  c=nlstools::confint2(fit)
  e=cbind(rep(name,3),rep(a,3),b,c)
  return(e)
}

param=rbind(am(fit_aff_ABC,"fit_aff_ABC"),
      am(fit_aff_BBC,"fit_aff_BBC"),
      am(fit_aff_SCS,"fit_aff_SCS"),
      am(fit_aff_TECS,"fit_aff_TECS"),
      am(fit_ref_ABC,"fit_ref_ABC"),
      am(fit_ref_BBC,"fit_ref_BBC"),
      am(fit_ref_SCS,"fit_ref_SCS"),
      am(fit_ref_TECS,"fit_ref_TECS"))
write.csv(param,"param_nls.csv") ### Table S4


ABC_ref_result=data.frame(investr::predFit(fit_ref_ABC,newdata=data.frame(Age=seq(0,40,by=1)),interval="confidence",level=0.95))
ABC_aff_result=data.frame(investr::predFit(fit_aff_ABC,newdata=data.frame(Age=seq(0,40,by=1)),interval="confidence",level=0.95))

BBC_ref_result=data.frame(investr::predFit(fit_ref_BBC,newdata=data.frame(Age=seq(0,40,by=1)),interval="confidence",level=0.95))
BBC_aff_result=data.frame(investr::predFit(fit_aff_BBC,newdata=data.frame(Age=seq(0,40,by=1)),interval="confidence",level=0.95))

SCS_ref_result=data.frame(investr::predFit(fit_ref_SCS,newdata=data.frame(Age=seq(0,40,by=1)),interval="confidence",level=0.95))
SCS_aff_result=data.frame(investr::predFit(fit_aff_SCS,newdata=data.frame(Age=seq(0,40,by=1)),interval="confidence",level=0.95))

TECS_ref_result=data.frame(investr::predFit(fit_ref_TECS,newdata=data.frame(Age=seq(0,40,by=1)),interval="confidence",level=0.95))
TECS_aff_result=data.frame(investr::predFit(fit_aff_TECS,newdata=data.frame(Age=seq(0,40,by=1)),interval="confidence",level=0.95))

mytheme=theme_bw()+
  theme(axis.text = element_text(family = "Helvetica",size=7),
  axis.text.x=element_text(face="plain",family = "Helvetica",size=7), 
        axis.text.y=element_text(face="plain",family = "Helvetica",size=7), 
        axis.title.y=element_text(face="plain",family = "Helvetica",size=7), 
        axis.title.x=element_text(face="plain",family = "Helvetica",size=7),  
        plot.title=element_text(hjust=0.5,vjust=0,family = "Helvetica",size=7),
        legend.text = element_text(family = "Helvetica",size=7),
        legend.title = element_text(face="plain",family = "Helvetica",size=7),
        panel.border = element_rect(fill=NA, size=0.4),
        legend.position = "bottom",
        strip.text.x = element_text(family = "Helvetica",size=7),
        panel.grid.major =element_blank(), 
        panel.grid.minor = element_blank(),
        axis.ticks = element_line(colour = 'black', size = 0.3))

year=c(0:40,0:40)
type=c(rep("reforestation",41),rep("afforestation",41))
TECS_all=cbind(year,rbind(TECS_ref_result,TECS_aff_result),type)

p1=ggplot(TECS_all,aes(x=year))+
  geom_point(data=TECS,aes(x=Age,y=TECS_mean,color=re_af),size=2, alpha=0.6)+
  geom_line(aes(x=year,y=fit,color=type),size=0.5,linetype=1)+
  geom_ribbon(aes(ymin=lwr,ymax=upr,fill=type),alpha=0.2)+
  scale_color_manual(values = c("reforestation"="#AD3818","afforestation"="#FCB29E"))+
  scale_fill_manual(values = c("reforestation"="#AD3818","afforestation"="#FCB29E"))+
  mytheme+
        scale_x_continuous(limits=c(0,45),expand = c(0,0))+
  scale_y_continuous(limits = c(0,600))+
        xlab("Mangrove age (Year)")+
        ylab(expression(paste("Carbon density (Mg C ha"^-1*")")))


year=c(0:40,0:40)
type=c(rep("reforestation",41),rep("afforestation",41))
ABC_all=cbind(year,rbind(ABC_ref_result,ABC_aff_result),type)

p2=ggplot(ABC_all,aes(x=year))+
    geom_point(data=ABC,aes(x=Age,y=ABC_mean,color=re_af),size=2, alpha=0.6)+
  geom_line(aes(x=year,y=fit,color=type),size=0.5,linetype=1)+
  geom_ribbon(aes(ymin=lwr,ymax=upr,fill=type),alpha=0.2)+
  scale_color_manual(values = c("reforestation"="#006400","afforestation"="#51C151"))+
  scale_fill_manual(values = c("reforestation"="#006400","afforestation"="#51C151"))+
  mytheme+
        scale_x_continuous(limits=c(0,45),expand = c(0,0))+
        xlab("Mangrove age (Year)")+
        ylab(expression(paste("Carbon density (Mg C ha"^-1*")")))


year=c(0:40,0:40)
type=c(rep("reforestation",41),rep("afforestation",41))
BBC_all=cbind(year,rbind(BBC_ref_result,BBC_aff_result),type)

p3=ggplot(BBC_all,aes(x=year))+
    geom_point(data=BBC,aes(x=Age,y=BBC_mean,color=re_af),size=2, alpha=0.6)+
  geom_line(aes(x=year,y=fit,color=type),size=0.5,linetype=1)+
  geom_ribbon(aes(ymin=lwr,ymax=upr,fill=type),alpha=0.2)+
  scale_color_manual(values = c("reforestation"="#09386C","afforestation"="#70ABEB"))+
  scale_fill_manual(values = c("reforestation"="#09386C","afforestation"="#70ABEB"))+
  mytheme+
        scale_x_continuous(limits=c(0,45),expand = c(0,0))+
        xlab("Mangrove age (Year)")+
        ylab(expression(paste("Carbon density (Mg C ha"^-1*")")))

year=c(0:40,0:40)
type=c(rep("reforestation",41),rep("afforestation",41))
SCS_all=cbind(year,rbind(SCS_ref_result,SCS_aff_result),type)

p5=ggplot(SCS_all,aes(x=year))+
    geom_point(data=SCS,aes(x=Age,y=SCS_mean_100,color=re_af),size=2, alpha=0.6)+
  geom_line(aes(x=year,y=fit,color=type),size=0.5,linetype=1)+
  geom_ribbon(aes(ymin=lwr,ymax=upr,fill=type),alpha=0.2)+
  scale_color_manual(values = c("reforestation"="#B8860B","afforestation"="#F3D33A"))+
  scale_fill_manual(values = c("reforestation"="#B8860B","afforestation"="#F3D33A"))+
  mytheme+
        scale_x_continuous(limits=c(0,45),expand = c(0,0))+
  scale_y_continuous(limits = c(0,550))+
        xlab("Mangrove age (Year)")+
        ylab(expression(paste("Carbon density (Mg C ha"^-1*")")))

TECS_ref_result=data.frame(investr::predFit(fit_ref_TECS,newdata=data.frame(Age=seq(0,40,by=1)),interval="confidence",level=0.95))
TECS_aff_result=data.frame(investr::predFit(fit_aff_TECS,newdata=data.frame(Age=seq(0,40,by=1)),interval="confidence",level=0.95))

TECS_ref_result[,1]=TECS_ref_result[,1]-TECS_ref_result[1,1]
TECS_ref_result[,2]=TECS_ref_result[,2]-TECS_ref_result[1,2]
TECS_ref_result[,3]=TECS_ref_result[,3]-TECS_ref_result[1,3]
TECS_aff_result[,1]=TECS_aff_result[,1]-TECS_aff_result[1,1]
TECS_aff_result[,2]=TECS_aff_result[,2]-TECS_aff_result[1,2]
TECS_aff_result[,3]=TECS_aff_result[,3]-TECS_aff_result[1,3]

year=c(0:40,0:40)
type=c(rep("reforestation",41),rep("afforestation",41))
TECS_all=cbind(year,rbind(TECS_ref_result,TECS_aff_result),type)

p4=ggplot(TECS_all,aes(x=year))+
  geom_line(aes(x=year,y=fit,color=type),size=1,linetype=1)+
  geom_ribbon(aes(ymin=lwr,ymax=upr,fill=type),alpha=0.2)+
  scale_color_manual(values = c("reforestation"="#AD3818","afforestation"="#FCB29E"))+
  scale_fill_manual(values = c("reforestation"="#AD3818","afforestation"="#FCB29E"))+
  mytheme+
        scale_x_continuous(limits=c(0,45),expand = c(0,0))+
  scale_y_continuous(limits = c(0,600))+
        xlab("Mangrove age (Year)")+
        ylab(expression(paste("Carbon density (Mg C ha"^-1*")")))

write.csv(ABC_all,"ABC_all.csv")
write.csv(BBC_all,"BBC_all.csv")
write.csv(SCS_all,"SCS_all.csv")
write.csv(TECS_all,"TECS_all.csv")


library("sf")
library("rnaturalearth")
library("rnaturalearthdata")
world = ne_countries(scale = "medium", returnclass = "sf")

world_tecs=read.csv("EEZ_mangroveloss_final.csv") ### file include mangrove loss area in each country/EEZ
world_tecs$reforestation.Tg.CO2_40=world_tecs$area.ha*(ABC_ref_result$fit[41]+BBC_ref_result$fit[41]+SCS_ref_result$fit[41]-SCS_ref_result$fit[1])/10^6/12*44

world_tecs$afforestation.Tg.CO2_40=world_tecs$area.ha*(ABC_aff_result$fit[41]+BBC_aff_result$fit[41]+SCS_aff_result$fit[41]-SCS_aff_result$fit[1])/10^6/12*44

world_tecs$reforestation.Tg.CO2_10=world_tecs$area.ha*(ABC_ref_result$fit[11]+BBC_ref_result$fit[11]+SCS_ref_result$fit[11]-SCS_ref_result$fit[1])/10^6/12*44

world_tecs$afforestation.Tg.CO2_10=world_tecs$area.ha*(ABC_aff_result$fit[11]+BBC_aff_result$fit[11]+SCS_aff_result$fit[11]-SCS_aff_result$fit[1])/10^6/12*44

world_tecs$reforestation.Tg.CO2_20=world_tecs$area.ha*(ABC_ref_result$fit[21]+BBC_ref_result$fit[21]+SCS_ref_result$fit[21]-SCS_ref_result$fit[1])/10^6/12*44

world_tecs$afforestation.Tg.CO2_20=world_tecs$area.ha*(ABC_aff_result$fit[21]+BBC_aff_result$fit[21]+SCS_aff_result$fit[21]-SCS_aff_result$fit[1])/10^6/12*44

world_tecs$reforestation.Tg.CO2_30=world_tecs$area.ha*(ABC_ref_result$fit[31]+BBC_ref_result$fit[31]+SCS_ref_result$fit[31]-SCS_ref_result$fit[1])/10^6/12*44

world_tecs$afforestation.Tg.CO2_30=world_tecs$area.ha*(ABC_aff_result$fit[31]+BBC_aff_result$fit[31]+SCS_aff_result$fit[31]-SCS_aff_result$fit[1])/10^6/12*44

world_tecs$reforestation.Tg.CO2_35=world_tecs$area.ha*(ABC_ref_result$fit[36]+BBC_ref_result$fit[36]+SCS_ref_result$fit[36]-SCS_ref_result$fit[1])/10^6/12*44

world_tecs$afforestation.Tg.CO2_35=world_tecs$area.ha*(ABC_aff_result$fit[36]+BBC_aff_result$fit[36]+SCS_aff_result$fit[36]-SCS_aff_result$fit[1])/10^6/12*44


world_tecs$reforestation.C_acum[1]=ABC_ref_result$fit[41]+BBC_ref_result$fit[41]+SCS_ref_result$fit[41]-SCS_ref_result$fit[1]
world_tecs$reforestation.C_acum[2]=ABC_ref_result$lwr[41]+BBC_ref_result$lwr[41]+SCS_ref_result$lwr[41]-SCS_ref_result$lwr[1]
world_tecs$reforestation.C_acum[3]=ABC_ref_result$upr[41]+BBC_ref_result$upr[41]+SCS_ref_result$upr[41]-SCS_ref_result$upr[1]
world_tecs$reforestation.C_acum_name[1]=c("41")

world_tecs$reforestation.C_acum[4]=sum(ABC_ref_result$fit[37:41])+sum(BBC_ref_result$fit[37:41])+sum(SCS_ref_result$fit[37:41])-SCS_ref_result$fit[1]*5
world_tecs$reforestation.C_acum[5]=sum(ABC_ref_result$lwr[37:41])+sum(BBC_ref_result$lwr[37:41])+sum(SCS_ref_result$lwr[37:41])-SCS_ref_result$lwr[1]*5
world_tecs$reforestation.C_acum[6]=sum(ABC_ref_result$upr[37:41])+sum(BBC_ref_result$upr[37:41])+sum(SCS_ref_result$upr[37:41])-SCS_ref_result$upr[1]*5
world_tecs$reforestation.C_acum_name[4]=c("37-41")

world_tecs$reforestation.C_acum[7]=sum(ABC_ref_result$fit[32:41])+sum(BBC_ref_result$fit[32:41])+sum(SCS_ref_result$fit[32:41])-SCS_ref_result$fit[1]*10
world_tecs$reforestation.C_acum[8]=sum(ABC_ref_result$lwr[32:41])+sum(BBC_ref_result$lwr[32:41])+sum(SCS_ref_result$lwr[32:41])-SCS_ref_result$lwr[1]*10
world_tecs$reforestation.C_acum[9]=sum(ABC_ref_result$upr[32:41])+sum(BBC_ref_result$upr[32:41])+sum(SCS_ref_result$upr[32:41])-SCS_ref_result$upr[1]*10
world_tecs$reforestation.C_acum_name[7]=c("32-41")

world_tecs$reforestation.C_acum[10]=sum(ABC_ref_result$fit[22:41])+sum(BBC_ref_result$fit[22:41])+sum(SCS_ref_result$fit[22:41])-SCS_ref_result$fit[1]*20
world_tecs$reforestation.C_acum[11]=sum(ABC_ref_result$lwr[22:41])+sum(BBC_ref_result$lwr[22:41])+sum(SCS_ref_result$lwr[22:41])-SCS_ref_result$lwr[1]*20
world_tecs$reforestation.C_acum[12]=sum(ABC_ref_result$upr[22:41])+sum(BBC_ref_result$upr[22:41])+sum(SCS_ref_result$upr[22:41])-SCS_ref_result$upr[1]*20
world_tecs$reforestation.C_acum_name[10]=c("22-41")

world_tecs$afforestation.C_acum[1]=ABC_aff_result$fit[41]+BBC_aff_result$fit[41]+SCS_aff_result$fit[41]-SCS_aff_result$fit[1]
world_tecs$afforestation.C_acum[2]=ABC_aff_result$lwr[41]+BBC_aff_result$lwr[41]+SCS_aff_result$lwr[41]-SCS_aff_result$lwr[1]
world_tecs$afforestation.C_acum[3]=ABC_aff_result$upr[41]+BBC_aff_result$upr[41]+SCS_aff_result$upr[41]-SCS_aff_result$upr[1]
world_tecs$afforestation.C_acum_name[1]=c("41")

world_tecs$afforestation.C_acum[4]=sum(ABC_aff_result$fit[37:41])+sum(BBC_aff_result$fit[37:41])+sum(SCS_aff_result$fit[37:41])-SCS_aff_result$fit[1]*5
world_tecs$afforestation.C_acum[5]=sum(ABC_aff_result$lwr[37:41])+sum(BBC_aff_result$lwr[37:41])+sum(SCS_aff_result$lwr[37:41])-SCS_aff_result$lwr[1]*5
world_tecs$afforestation.C_acum[6]=sum(ABC_aff_result$upr[37:41])+sum(BBC_aff_result$upr[37:41])+sum(SCS_aff_result$upr[37:41])-SCS_aff_result$upr[1]*5
world_tecs$afforestation.C_acum_name[4]=c("37-41")

world_tecs$afforestation.C_acum[7]=sum(ABC_aff_result$fit[32:41])+sum(BBC_aff_result$fit[32:41])+sum(SCS_aff_result$fit[32:41])-SCS_aff_result$fit[1]*10
world_tecs$afforestation.C_acum[8]=sum(ABC_aff_result$lwr[32:41])+sum(BBC_aff_result$lwr[32:41])+sum(SCS_aff_result$lwr[32:41])-SCS_aff_result$lwr[1]*10
world_tecs$afforestation.C_acum[9]=sum(ABC_aff_result$upr[32:41])+sum(BBC_aff_result$upr[32:41])+sum(SCS_aff_result$upr[32:41])-SCS_aff_result$upr[1]*10
world_tecs$afforestation.C_acum_name[7]=c("32-41")

world_tecs$afforestation.C_acum[10]=sum(ABC_aff_result$fit[22:41])+sum(BBC_aff_result$fit[22:41])+sum(SCS_aff_result$fit[22:41])-SCS_aff_result$fit[1]*20
world_tecs$afforestation.C_acum[11]=sum(ABC_aff_result$lwr[22:41])+sum(BBC_aff_result$lwr[22:41])+sum(SCS_aff_result$lwr[22:41])-SCS_aff_result$lwr[1]*20
world_tecs$afforestation.C_acum[12]=sum(ABC_aff_result$upr[22:41])+sum(BBC_aff_result$upr[22:41])+sum(SCS_aff_result$upr[22:41])-SCS_aff_result$upr[1]*20
world_tecs$afforestation.C_acum_name[10]=c("22-41")

write.csv(world_tecs,"EEZ_mangroveloss_final.csv")

world_tecs_com=merge(world,world_tecs,by.x="admin",by.y="country")

area_total=sum(world_tecs$area.ha)-274.5553681


all=data.frame(x=c(1,1,1,1,1,1,1,1),
                 class=c("afforestation",
                       "afforestation",
                       "afforestation",
                       "afforestation",
                       "reforestation",
                       "reforestation",
                       "reforestation",
                       "reforestation"),
               ob=c("ABC","BBC","SCS","TECS","ABC_1","BBC_1","SCS_1","TECS_1"),
               data=c(ABC_aff_result$fit[41],
                      -(BBC_aff_result$fit[41]),
                      -(SCS_aff_result$fit[41]-SCS_aff_result$fit[1]),
                      0,
                      ABC_ref_result$fit[41],
                      -(BBC_ref_result$fit[41]),
                      -(SCS_ref_result$fit[41]-SCS_ref_result$fit[1]),
                      0),
               data_lower=c(ABC_aff_result$lwr[41],
                      -(BBC_aff_result$lwr[41]),
                      -(SCS_aff_result$lwr[41]-SCS_aff_result$lwr[1]+BBC_aff_result$fit[41]),
                      0,
                      ABC_ref_result$lwr[41],
                      -(BBC_ref_result$lwr[41]),
                      -(SCS_ref_result$lwr[41]-SCS_ref_result$lwr[1]+BBC_ref_result$fit[41]),
                      0),
               data_upper=c(ABC_aff_result$upr[41],
                      -(BBC_aff_result$upr[41]),
                      -(SCS_aff_result$upr[41]-SCS_aff_result$upr[1]+BBC_aff_result$fit[41]),
                      0,
                      ABC_ref_result$upr[41],
                      -(BBC_ref_result$upr[41]),
                      -(SCS_ref_result$upr[41]-SCS_ref_result$upr[1]+BBC_ref_result$fit[41]),
                      0))

write.csv(all,"all_stimulate_40.csv")

all$data=all$data*area_total/10^6/12*44
all$data_lower=all$data_lower*area_total/10^6/12*44
all$data_upper=all$data_upper*area_total/10^6/12*44


p7=ggplot(all,aes(x=class,y=data,fill=ob))+
  geom_bar(stat = "identity") +
  mytheme+
  theme(
        axis.title.x=element_blank(), 
        legend.key.size = unit(5, 'mm'),
        legend.position = "bottom",
        panel.background = element_rect(fill = "transparent",color=NA), 
        plot.background = element_rect(fill = "transparent", color = NA),
        panel.grid.major = element_blank(), 
        panel.grid.minor = element_blank(),
        legend.background = element_rect(fill = "transparent"), 
        legend.box.background = element_rect(fill = "transparent"),
        axis.line = element_line(colour = "black"))+ 
  scale_y_continuous(expand = c(0,0),limits = c(-500,500))+
  scale_fill_manual(values = c("#51C151","#006400","#70ABEB","#09386C","#F3D33A","#B8860B","#FCB29E","#AD3818"),
                    labels=c("ABC","ABC","BBC","BBC","SCS","SCS","TECS","TECS"),
                    name=expression(atop("Afforestation",
                                         atop(textstyle("Reforestation")))))+
  guides(alpha=FALSE)

leg = get_legend(p7)
p8=as_ggplot(leg)+theme(panel.background = element_rect(fill = "transparent",color=NA), 
        plot.background = element_rect(fill = "transparent", color = NA),
        panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        legend.background = element_rect(fill = "transparent", color = NA),
        panel.border = element_rect(fill = "transparent", color = NA),
        rect = element_rect(fill = "transparent")) 
p8

all$ob=factor(all$ob,levels = c("ABC","SCS","BBC","TECS","ABC_1","SCS_1","BBC_1","TECS_1"))

p6=ggplot(all,aes(x=class,y=data,fill=ob))+
  geom_bar(color="lightgrey",stat = "identity",lwd=0.3) +
  geom_errorbar(aes(ymin= data_lower,
                    ymax= data_upper),
                width=.1,
                position="identity",
                lwd=0.3)+
  mytheme+
  theme(
    axis.text.x = element_text(size=5),
    axis.text.y = element_text(size=5),
    axis.title.y=element_text(size=5),
        axis.title.x=element_blank(), 
        legend.position = "none",
        panel.background = element_rect(fill = "transparent",color=NA), 
        plot.background = element_rect(fill = "transparent", color = NA),
        panel.grid.major = element_blank(), 
        panel.grid.minor = element_blank(),
        legend.background = element_rect(fill = "transparent"), 
        legend.box.background = element_rect(fill = "transparent"),
        axis.line = element_line(colour = "black"))+ 
  geom_hline(yintercept=0)+
  ylab(expression(atop("Global carbon sequestration",paste("potential (Tg CO"[2]*"-eq)"))))+
  scale_fill_manual(values = c("#51C151","#F3D33A","#70ABEB","#FCB29E","#006400","#B8860B","#09386C","#AD3818"),
                    labels=c("ABC","SCS","BBC","TECS","ABC","SCS","BBC","TECS"),
                    name=expression(atop("Afforestation",
                                         atop(textstyle("Reforestation")))))+
  guides(alpha=FALSE)
p6



onlyfrance=ne_countries(geounit = 'france', type = 'map_units',
                        scale = "medium", returnclass = "sf")

p9=ggplot(data = world_tecs_com) +
    geom_sf(data=world,color = "#EEEEEE", fill = "#E3E3E3",lwd=0.3)+
    geom_sf(aes(fill = reforestation.Tg.CO2_40),alpha=0.8,lwd=0.3) +
    geom_sf(data=onlyfrance,color="#EEEEEE",fill="#E3E3E3",lwd=0.3)+
    scale_fill_gradient2(low="#F3CABE",mid="#9B4C35", high="#692410", midpoint = 110, space ="Lab",na.value="white")+
  mytheme+
    theme(
        panel.grid.major =element_blank(), 
        panel.grid.minor = element_blank(),
        legend.background = element_blank(),
        legend.key.width = unit(1.2, "cm"),
        legend.key.height = unit(5,"mm"),
        legend.direction = "horizontal",
        legend.position = "bottom",
        legend.justification = "right",
          legend.margin = margin(t = 2, r = 0, b = 2, l = 2, unit = "mm"))+
  scale_x_continuous(expand = c(0,0))+
  scale_y_continuous(expand = c(0,0),limits = c(-48,55))+
    xlab("Longitude")+
    ylab("Latitude")+
  annotation_custom(
    ggplotGrob(p6), 
    xmin = -180, xmax = -85, ymin = -50, ymax = 15)+
  annotation_custom(
    ggplotGrob(p8), 
    xmin = -135, xmax = -80, ymin = -100, ymax = -70)+
  labs(fill=expression(atop("Carbon sequestration potential",
                                         atop(textstyle("for mangrove reforestation"),
                                             atop(textstyle(("Tg CO"[2]*"-eq")))))))
  

ggarrange(ggarrange(p2,p3,p5,p1,nrow=1,labels = c("a","b","c","d"),legend='none',font.label=list(face="plain",family = "Helvetica",size=7,face="bold")),
          p9,ncol=1,nrow=2,labels=c("","e"),heights = c(1,2.5),font.label=list(face="plain",family = "Helvetica",size=7,face="bold"))

ggsave(path = "[Please change it to your own path]",
       filename="Fig.4.png",
       width = 180, height = 135, units = "mm",dpi=300)

```

```{r}
## Fig. S1 ###
species=data%>%
  filter(plant_nature!="")%>%
  filter(group=="restored")%>%
  filter(ABC_mean!=""|BBC_mean!=""|SCS_mean_100!="")%>%
  filter(Species_2!="")

species%>%freq_table(re_af,Species_2)

A=as.data.frame(table(species$plant_nature,species$Species_2,species$re_af))
B=as.data.frame(table(species$Species_2,species$re_af))
write.csv(A,"species_frequency.csv")


A$Var1=gsub("nature","natural",A$Var1)

A$Var1=factor(A$Var1,levels = c("plant","natural"))

p1=ggplot(A,aes(y = Freq, axis1=Var1, axis3 = Var2, axis2 = Var3)) +
    geom_alluvium(aes(fill = Var3)) +
    geom_stratum(aes(fill = Var3),alpha = .2) +
    scale_fill_brewer(type = "qual", palette = "Set1")+
    theme_void()+
    #coord_flip()+ 
    guides(fill = FALSE)+
  theme(plot.title=element_text(hjust=0.5,size=15))+
  ggrepel::geom_text_repel(
  aes(label = ifelse(after_stat(x) == 3, as.character(after_stat(stratum)), "")),
  stat = "stratum", size = 3.6, family = "Helvetica",direction = "y", nudge_x = 0.7)+
  ggrepel::geom_text_repel(
    aes(label = ifelse(after_stat(x)  == 2, as.character(after_stat(stratum)), "")),
    stat = "stratum", size = 3.6,family = "Helvetica", direction = "y", nudge_x = 0)+
    ggrepel::geom_text_repel(
    aes(label = ifelse(after_stat(x)  == 1, as.character(after_stat(stratum)), "")),
    stat = "stratum", size = 3.6,family = "Helvetica", direction = "y", nudge_x = 0)
p1

ggsave(path = "[Please change it to your own path]",
       filename="Fig.S1.png",
       width = 180, height = 170, units = "mm",dpi=300)

```

```{r}
### Fig. S11 ###
ABC_ref=ABC%>%filter(re_af=="reforestation")%>%arrange(Age)%>%filter(Age<=40)
ABC_aff=ABC%>%filter(re_af=="afforestation")%>%arrange(Age)%>%filter(Age<=40)

# VB
VB=function(x,Asym,K,t0) Asym*(1-exp(-K*(x-t0)))
fit_ref_vb = nls(ABC_mean~VB(Age,Asym,K,t0),data=ABC_ref,start=list(Asym=115.72,K=1,t0=2.43))
fit_aff_vb = nls(ABC_mean~VB(Age,Asym,K,t0),data=ABC_aff,start=list(Asym=91.55,K=1,t0=2.43))

# Gompertz Growth Model
Gompertz = function(x, Asym, b2, b3) Asym*exp(-b2*b3^x)
fit_ref_g = nls(ABC_mean~Gompertz(Age,Asym,b2,b3),data=ABC_ref,start=list(Asym=115.72,b2=1.4,b3=0.95))
fit_aff_g = nls(ABC_mean~Gompertz(Age,Asym,b2,b3),data=ABC_aff,start=list(Asym=91.55,b2=1.4,b3=0.9))

# Chapman-Richards Model
chapm = function(x,Asym,b,c)Asym*(1-exp(-b*x))^c
fit_ref_cr= nls(ABC_mean~chapm(Age,Asym,b,c),data=ABC_ref,start=list(Asym=125,b=0.05,c=1)) #100
fit_aff_cr = nls(ABC_mean~chapm(Age,Asym,b,c),data=ABC_aff,start=list(Asym=80,b=0.1,c=2)) #100

a=print(IC_tab(fit_ref_vb,fit_ref_g,fit_ref_cr), digits = 2)
b=print(IC_tab(fit_aff_vb,fit_aff_g,fit_aff_cr), digits = 2)

rownames(a)[rownames(a)=="1"]="Von Bertalanffy model"
rownames(a)[rownames(a)=="2"]="Gompertz growth model"
rownames(a)[rownames(a)=="3"]="Chapman-Richards model"

rownames(b)[rownames(b)=="1"]="Von Bertalanffy model"
rownames(b)[rownames(b)=="2"]="Gompertz growth model"
rownames(b)[rownames(b)=="3"]="Chapman-Richards model"

ABC_ref_r=data.frame(model=rownames(a),AIC=a$AIC)
ABC_aff_r=data.frame(model=rownames(b),AIC=b$AIC)

BBC_ref=BBC%>%filter(re_af=="reforestation")%>%arrange(Age)%>%filter(Age<=40)
BBC_aff=BBC%>%filter(re_af=="afforestation")%>%arrange(Age)%>%filter(Age<=40)

# VB
VB=function(x,Asym,K,t0) Asym*(1-exp(-K*(x-t0)))
fit_ref_vb = nls(BBC_mean~VB(Age,Asym,K,t0),data=BBC_ref,start=list(Asym=80,K=1,t0=2.43))
fit_aff_vb = nls(BBC_mean~VB(Age,Asym,K,t0),data=BBC_aff,start=list(Asym=90,K=1,t0=3))

# Gompertz Growth Model
Gompertz = function(x, Asym, b2, b3) Asym*exp(-b2*b3^x)
fit_ref_g = nls(BBC_mean~Gompertz(Age,Asym,b2,b3),data=BBC_ref,start=list(Asym=95.56,b2=2.74,b3=0.96))
fit_aff_g = nls(BBC_mean~Gompertz(Age,Asym,b2,b3),data=BBC_aff,start=list(Asym=75,b2=2,b3=0.96))

# Chapman-Richards Model
chapm = function(x,Asym,b,c)Asym*(1-exp(-b*x))^c
fit_ref_cr= nls(BBC_mean~chapm(Age,Asym,b,c),data=BBC_ref,start=list(Asym=95.56,b=0.1,c=1)) #100
fit_aff_cr = nls(BBC_mean~chapm(Age,Asym,b,c),data=BBC_aff,start=list(Asym=55, b=0.1, c=1)) #100

a=print(IC_tab(fit_ref_vb,fit_ref_g,fit_ref_cr), digits = 2)
b=print(IC_tab(fit_aff_vb,fit_aff_g,fit_aff_cr), digits = 2)

rownames(a)[rownames(a)=="1"]="Von Bertalanffy model"
rownames(a)[rownames(a)=="2"]="Gompertz growth model"
rownames(a)[rownames(a)=="3"]="Chapman-Richards model"

rownames(b)[rownames(b)=="1"]="Von Bertalanffy model"
rownames(b)[rownames(b)=="2"]="Gompertz growth model"
rownames(b)[rownames(b)=="3"]="Chapman-Richards model"

BBC_ref_r=data.frame(model=rownames(a),AIC=a$AIC)
BBC_aff_r=data.frame(model=rownames(b),AIC=b$AIC)



SCS_ref=SCS%>%filter(re_af=="reforestation")%>%arrange(Age)
SCS_aff=SCS%>%filter(re_af=="afforestation")%>%arrange(Age)

# VB
VB=function(x,Asym,K,t0) Asym*(1-exp(-K*(x-t0)))
fit_ref_vb = nls(SCS_mean_100~VB(Age,Asym,K,t0),data=SCS_ref,start=list(Asym=460,K=0.059,t0=89))
fit_aff_vb = nls(SCS_mean_100~VB(Age,Asym,K,t0),data=SCS_aff,start=list(Asym=150,K=0.1,t0=10))


# Gompertz Growth Model
Gompertz = function(x, Asym, b2, b3) Asym*exp(-b2*b3^x)
fit_ref_g = nls(SCS_mean_100~Gompertz(Age,Asym,b2,b3),data=SCS_ref,start=list(Asym=510,b2=0.3,b3=0.9))
fit_aff_g = nls(SCS_mean_100~Gompertz(Age,Asym,b2,b3),data=SCS_aff,start=list(Asym=240,b2=0.67,b3=0.9))

a=print(IC_tab(fit_ref_vb,fit_ref_g), digits = 2)
b=print(IC_tab(fit_aff_vb,fit_aff_g), digits = 2)


rownames(a)[rownames(a)=="1"]="Von Bertalanffy model"
rownames(a)[rownames(a)=="2"]="Gompertz growth model"

rownames(b)[rownames(b)=="1"]="Von Bertalanffy model"
rownames(b)[rownames(b)=="2"]="Gompertz growth model"

SCS_ref_r=data.frame(model=rownames(a),AIC=a$AIC)
SCS_aff_r=data.frame(model=rownames(b),AIC=b$AIC)

TECS_ref=TECS%>%filter(re_af=="reforestation")%>%arrange(Age)
TECS_aff=TECS%>%filter(re_af=="afforestation")%>%arrange(Age)


# VB
VB=function(x,Asym,K,t0) Asym*(1-exp(-K*(x-t0)))
fit_ref_vb = nls(TECS_mean~VB(Age,Asym,K,t0),data=TECS_ref,start=list(Asym=500,K=0.1,t0=100))
fit_aff_vb = nls(TECS_mean~VB(Age,Asym,K,t0),data=TECS_aff,start=list(Asym=270,K=0.1,t0=10))


# Gompertz Growth Model
Gompertz = function(x, Asym, b2, b3) Asym*exp(-b2*b3^x)
# fit_ref_g = nls(TECS_mean~Gompertz(Age,Asym,b2,b3),data=TECS_ref,start=list(Asym=450,b2=1.2,b3=0.9))
fit_ref_g = nls(TECS_mean~Gompertz(Age,Asym,b2,b3),data=TECS_ref,start=list(Asym=450,b2=0.8,b3=0.9))
fit_aff_g = nls(TECS_mean~Gompertz(Age,Asym,b2,b3),data=TECS_aff,start=list(Asym=200,b2=1.4,b3=0.9))


a=print(IC_tab(fit_ref_vb,fit_ref_g), digits = 2)
b=print(IC_tab(fit_aff_vb,fit_aff_g), digits = 2)

rownames(a)[rownames(a)=="1"]="Von Bertalanffy model"
rownames(a)[rownames(a)=="2"]="Gompertz growth model"

rownames(b)[rownames(b)=="1"]="Von Bertalanffy model"
rownames(b)[rownames(b)=="2"]="Gompertz growth model"

TECS_ref_r=data.frame(model=rownames(a),AIC=a$AIC)
TECS_aff_r=data.frame(model=rownames(b),AIC=b$AIC)

ref_r=cbind(rbind(ABC_ref_r,BBC_ref_r,SCS_ref_r,TECS_ref_r),type=c(rep("ABC",3),rep("BBC",3),rep("SCS",2),rep("TECS",2)))
aff_r=cbind(rbind(ABC_aff_r,BBC_aff_r,SCS_aff_r,TECS_aff_r),type=c(rep("ABC",3),rep("BBC",3),rep("SCS",2),rep("TECS",2)))

r=cbind(rbind(ref_r,aff_r),group=c(rep("reforestation",10),rep("afforestation",10)))

mytheme=theme_bw()+
  theme(axis.text = element_text(family = "Helvetica",size=6),
  axis.text.x=element_text(face="plain",family = "Helvetica",size=6), 
        axis.text.y=element_text(face="plain",family = "Helvetica",size=6), 
        axis.title.y=element_text(face="plain",family = "Helvetica",size=6), 
        axis.title.x=element_text(face="plain",family = "Helvetica",size=6),  
        plot.title=element_text(hjust=0.5,vjust=0,family = "Helvetica",size=6),
        legend.text = element_text(family = "Helvetica",size=6),
        legend.title = element_text(face="plain",family = "Helvetica",size=6),
        panel.border = element_rect(fill=NA, size=0.4),
        legend.position = "bottom",
        strip.text.x = element_text(family = "Helvetica",size=6),
        panel.grid.major =element_blank(), 
        panel.grid.minor = element_blank(),
        axis.ticks = element_line(colour = 'black', size = 0.3),
        legend.margin=margin(0,0,0,0),
        legend.box.margin=margin(-5,0,-5,0))


a=ggplot(ref_r,aes(x=model,y=AIC,color=model))+
  geom_point(size=3,alpha=0.6)+ 
  mytheme+
    theme(
        axis.text.x=element_blank(),
        axis.title.x=element_text(face="plain",color="white"),
        legend.title=element_blank(),
        legend.position = "bottom",
        panel.grid.major =element_blank(),
        panel.grid.minor = element_blank(),
        strip.background = element_rect(fill="transparent",color=NA))+
  facet_wrap(~type,scales = "free_y",nrow=4)+
  ylab("AIC")

b=ggplot(aff_r,aes(x=model,y=AIC,color=model))+
  geom_point(size=3,alpha=0.6)+ 
  mytheme+
    theme(
          axis.title.y=element_text(color="white"),
        axis.text.x=element_blank(),
        axis.title.x=element_text(face="plain",color="white"),
        legend.title=element_blank(),
        legend.position = "bottom",
        panel.grid.major =element_blank(),
        panel.grid.minor = element_blank(),
        strip.background = element_rect(fill="transparent",color=NA))+
  facet_wrap(~type,scales = "free_y",nrow=4)+
  ylab("AIC")

ggarrange(a,b,ncol=2,labels=c("a","b"),common.legend = T,legend = "bottom",font.label=list(face="plain",family = "Helvetica",size=6,face="bold"))

ggsave(path = "[Please change it to you own path]",
       filename="Fig.S11.png",
       width = 110, height = 120, units = "mm")
```


```{r}
### Fig. S5 ###
data=read.csv("Supplementary Data1221.csv",stringsAsFactors = FALSE,fileEncoding="latin1")

data=data%>%
  filter(ID<1000)%>%  # delete abnormal data
  filter(re_af!="")%>%
  filter(group!="intact")%>%
  mutate(re_af=factor(re_af,level=c("afforestation","reforestation")))

colnames(data)[c(19:24,26,28:33,35)]=c("BC_mean","ABC_mean","BBC_mean",
                                    "SCS_mean","SCS_mean_100","SCS_increase_all",
                                       "SC_mean","TECS_mean",
                                       "salinity_pore",
                                       "sand","silt","clay",
                                       "TN_mean","N.concentration_mean")   ## simplify column names
data$SC_mean=as.numeric(data$SC_mean)

mytheme=theme_bw()+
  theme(axis.text = element_text(family = "Helvetica",size=7),
  axis.text.x=element_text(face="plain",family = "Helvetica",size=7), 
        axis.text.y=element_text(face="plain",family = "Helvetica",size=7), 
        axis.title.y=element_text(face="plain",family = "Helvetica",size=7), 
        axis.title.x=element_text(face="plain",family = "Helvetica",size=7),  
        plot.title=element_text(hjust=0.5,vjust=0,family = "Helvetica",size=7),
        legend.text = element_text(family = "Helvetica",size=7),
        legend.title = element_text(face="plain",family = "Helvetica",size=7),
        panel.border = element_rect(fill=NA, size=0.4),
        legend.position = "bottom",
        strip.text.x = element_text(family = "Helvetica",size=7),
        panel.grid.major =element_blank(), 
        panel.grid.minor = element_blank(),
        axis.ticks = element_line(colour = 'black', size = 0.3))

# function for number of observations 
give.n <- function(x){
  return(data.frame(y = -2, label =  paste('italic(n) ==', length(x))))
  # experiment with the multiplier to find the perfect position
}


p6=ggboxplot(data,x="re_af",y="silt",
          color = "re_af", 
          add = "jitter", 
          legend = "none",
          add.params = list(alpha = 0.5))+
  stat_compare_means(size=2.5,aes(label = ifelse(p <= 0.001,
                                               paste("italic(P)<=","0.001"),
                                               paste("italic(P)==",round(as.numeric(..p.format..),3)))),
                     label.x=1.5,label.y = 85,hide.ns = TRUE,show.legend = F,parse=TRUE)+
      stat_summary(fun.data = give.n, geom = "text", fun.y = median, size=2.5,aes(color=re_af),
                   position = position_dodge(width = 0.75),parse=TRUE)+
  mytheme+
   theme(
        axis.text.x=element_blank(), 
        axis.title.x=element_text(face="plain",color="white"), 
        plot.title=element_text(hjust=0.5,colour = "white"),
        legend.title=element_blank(),
        panel.grid.major =element_blank(), 
        panel.grid.minor = element_blank()) +
  scale_y_continuous(limits = c(-5,90))+
  ylab("sediment silt content (%)")

p7=ggboxplot(data,x="re_af",y="sand",
          color = "re_af", 
          add = "jitter", 
          legend = "none",
          add.params = list(alpha = 0.5))+
  stat_compare_means(size=2.5,aes(label = ifelse(p <= 0.001,
                                               paste("italic(P)<=","0.001"),
                                               paste("italic(P)==",round(as.numeric(..p.format..),3)))),
                     label.x=1.5,label.y = 85,hide.ns = TRUE,show.legend = F,parse=TRUE)+
      stat_summary(fun.data = give.n, geom = "text", fun.y = median, size=2.5,aes(color=re_af),
                   position = position_dodge(width = 0.75),parse=TRUE)+
  mytheme+
  theme(
        axis.text.x=element_blank(), 
        axis.title.x=element_text(face="plain",color="white"), 
        plot.title=element_text(hjust=0.5,colour = "white"),
        legend.title=element_blank(),
        panel.grid.major =element_blank(), 
        panel.grid.minor = element_blank())+
  scale_y_continuous(limits = c(-5,90))+
  ylab("sediment sand content (%)")

p8=ggboxplot(data,x="re_af",y="clay",
          color = "re_af", 
          add = "jitter", 
          legend = "none",
          add.params = list(alpha = 0.5))+
  mytheme+
  stat_compare_means(size=2.5,aes(label = ifelse(p <= 0.001,
                                               paste("italic(P)<=","0.001"),
                                               paste("italic(P)==",round(as.numeric(..p.format..),3)))),
                     label.x=1.5,label.y = 85,hide.ns = TRUE,show.legend = F,parse=TRUE)+
      stat_summary(fun.data = give.n, geom = "text", fun.y = median, size=2.5,aes(color=re_af),
                   position = position_dodge(width = 0.75),parse=TRUE)+
  theme(
        axis.text.x=element_blank(), 
        axis.title.x=element_text(face="plain",color="white"), 
        plot.title=element_text(hjust=0.5,colour = "white"),
        legend.title=element_blank(),
        panel.grid.major =element_blank(), 
        panel.grid.minor = element_blank())+
  scale_y_continuous(limits = c(-5,90))+
  ylab("sediment clay content (%)")


data=data%>%filter(group=="initial")

# function for number of observations 
give.n <- function(x){
  return(data.frame(y = -1, label =  paste('italic(n) ==', length(x))))
  # experiment with the multiplier to find the perfect position
}

P1=ggboxplot(data,x="re_af",y="initial_SC",
          color = "re_af", 
          add = "jitter", 
          legend = "none",
          add.params = list(alpha = 0.5))+
  stat_compare_means(size=2.5,aes(label = ifelse(p <= 0.001,
                                               paste("italic(P)<=","0.001"),
                                               paste("italic(P)==",round(as.numeric(..p.format..),3)))),
                     label.x=1.5,label.y = 19,hide.ns = TRUE,show.legend = F,parse=TRUE)+
      stat_summary(fun.data = give.n, geom = "text", fun.y = median, size=2.5,aes(color=re_af),
                   position = position_dodge(width = 0.75),parse=TRUE)+
  mytheme+
    theme(
        axis.text.x=element_blank(), 
        axis.title.x=element_text(face="plain",color="white"), 
        plot.title=element_text(hjust=0.5,colour = "white"),
        legend.title=element_blank(),
        panel.grid.major =element_blank(), 
        panel.grid.minor = element_blank())+
  scale_y_continuous(limits = c(-2,20))+
  ylab("initial sediment TOC content (%)")

# function for number of observations 
give.n <- function(x){
  return(data.frame(y = -0.05, label =  paste('italic(n) ==', length(x))))
  # experiment with the multiplier to find the perfect position
}


P2=ggboxplot(data,x="re_af",y="initial_N",
          color = "re_af", 
          add = "jitter", 
          legend = "none",
          add.params = list(alpha = 0.5))+
  stat_compare_means(size=2.5,aes(label = ifelse(p <= 0.001,
                                               paste("italic(P)<=","0.001"),
                                               paste("italic(P)==",round(as.numeric(..p.format..),3)))),
                     label.x=1.5,hide.ns = TRUE,show.legend = F,parse=TRUE)+
        stat_summary(fun.data = give.n, geom = "text", fun.y = median, size=2.5,aes(color=re_af),
                   position = position_dodge(width = 0.75),parse=TRUE)+
  mytheme+theme(
        axis.text.x=element_blank(), 
        axis.title.x=element_text(face="plain",color="white"), 
        plot.title=element_text(hjust=0.5,colour = "white"),
        legend.title=element_blank(),
        panel.grid.major =element_blank(), 
        panel.grid.minor = element_blank())+
  scale_y_continuous(limits = c(-0.08,0.5))+
  ylab("initial sediment TN content (%)")

# function for number of observations 
give.n <- function(x){
  return(data.frame(y = 2, label =  paste('italic(n) ==', length(x))))
  # experiment with the multiplier to find the perfect position
}


P3=ggboxplot(data,x="re_af",y="initial_CN",
          color = "re_af", 
          add = "jitter", 
          legend = "none",
          add.params = list(alpha = 0.5))+
  stat_compare_means(size=2.5, aes(label =ifelse(p <= 0.001,
                                               paste("italic(P)<=","0.001"),
                                               paste("italic(P)==",round(as.numeric(..p.format..),3)))),
                     label.x=1.5,label.y=39,hide.ns = TRUE,show.legend = F,parse=TRUE)+
  stat_summary(fun.data = give.n, geom = "text", fun.y = median, size=2.5,aes(color=re_af),
                   position = position_dodge(width = 0.75),parse=TRUE)+
  mytheme+
  theme(
        axis.text.x=element_blank(), 
        axis.title.x=element_text(face="plain",color="white"), 
        plot.title=element_text(hjust=0.5,colour = "white"),
        legend.title=element_blank(),
        panel.grid.major =element_blank(), 
        panel.grid.minor = element_blank())+
  scale_y_continuous(limits = c(0,40))+
  ylab("initial sediment C:N")

ggarrange(p7,p6,p8,P1,P2,P3, ncol = 3, nrow =2 ,labels="auto",common.legend = TRUE,legend="bottom",font.label=list(face="plain",family = "Helvetica",size=7,face="bold"))

ggsave("Fig.S5.png", 
       path ="[please change it into your own path]",
       width = 180,height = 140,units = c("mm"),dpi = 300)


```

```{r}
### Fig. S8 ###
data=read.csv("Supplementary Data of Fig. S8.csv",stringsAsFactors = FALSE,fileEncoding = 'GB18030')

data=data%>%
  filter(plant_nature!="")%>%
  filter(Species_SP=="K")%>%
  mutate(re_af=factor(re_af,levels = c("reforestation","afforestation")))

ABC=data%>% drop_na(ABC_mean)%>%mutate_all(type.convert)

BBC=data%>% drop_na(BBC_mean)%>%mutate_all(type.convert)

SCS=data%>% drop_na(SCS_mean_100)%>%mutate_all(type.convert)

mytheme=theme_bw()+
  theme(axis.text = element_text(family = "Helvetica",size=7),
  axis.text.x=element_text(face="plain",family = "Helvetica",size=7), 
        axis.text.y=element_text(face="plain",family = "Helvetica",size=7), 
        axis.title.y=element_text(face="plain",family = "Helvetica",size=7), 
        axis.title.x=element_text(face="plain",family = "Helvetica",size=7),  
        plot.title=element_text(hjust=0.5,vjust=0,family = "Helvetica",size=7),
        legend.text = element_text(family = "Helvetica",size=7),
        legend.title = element_text(face="plain",family = "Helvetica",size=7),
        panel.border = element_rect(fill=NA, size=0.4),
        legend.position = "bottom",
        strip.text.x = element_text(family = "Helvetica",size=7),
        panel.grid.major =element_blank(), 
        panel.grid.minor = element_blank(),
        axis.ticks = element_line(colour = 'black', size = 0.3),
      # legend.key.size = unit(0.5,"mm"),
        legend.margin=margin(0,0,0,0),
        legend.box.margin=margin(-5,0,-5,0))


ABC$ID=factor(ABC$ID,levels=c("4 yr, newly-sedimentary tidal flat, Vietnam (20.2°N)",
                                 "5 yr, newly-sedimentary tidal flat, Vietnam (20.6°N)",
                                 "6 yr, newly-sedimentary tidal flat, Vietnam (20.6°N)",
                                 "3 yr, abandonded ponds, Vietnam (20.2°N)",
                                 "3 yr, abandonded ponds, China (22.7°N)",
                                 "5 yr, abandonded ponds, India (20.4°N)"))

BBC$ID=factor(BBC$ID,levels=c("3 yr, newly-sedimentary tidal flat, Vietnam (20.7°N)",
                                 "4 yr, newly-sedimentary tidal flat, Vietnam (20.2°N)",
                                 "5 yr, newly-sedimentary tidal flat, Vietnam (20.7°N)",
                                 "3 yr, abandonded ponds, Vietnam (20.2°N)",
                                 "3 yr, abandonded ponds, China (22.7°N)",
                                 "5 yr, abandonded ponds, India (20.4°N)"))

### test of normality and homogeneity of model residuals
ano=aov(ABC_mean~re_af,data=ABC)

plot(ano,1)
leveneTest(ABC_mean~re_af,data=ABC)

# normality of residuals
plot(ano, 2)
aov_residuals <- residuals(object = ano)
shapiro.test(x = aov_residuals)
## significant in the test of normality and homoscedasticity of model residuals


ABC_sum=ABC%>%group_by(re_af)%>%
  summarise(average = mean(ABC_mean),
                   std=sd(ABC_mean,na.rm = TRUE)/sqrt(length(ABC_mean)),
                   median=median(ABC_mean))%>%ungroup()

# function for number of observations 
give.n <- function(x){
  return(data.frame(y = 0.5, label =  paste('italic(n) ==', length(x))))
  # experiment with the multiplier to find the perfect position
}

P1=ggplot(data=ABC,aes(x=re_af,y=ABC_mean))+
  geom_jitter(data=ABC,aes(x=re_af,y=ABC_mean,size=Age,shape=ID),
                      color="grey",alpha=0.6,size=2,position = position_jitter(0.21))+
  stat_compare_means(size=2.5,aes(label = sprintf("italic(P)==%0.4f",as.numeric(..p.format..))),
                     label.x=1.5,show.legend = F,parse=TRUE)+
  stat_summary(aes(col = re_af), fun.data = "mean_se", geom = "errorbar", width=0.3)+
  stat_summary(fun.data = give.n, geom = "text", fun.y = median, size=2.5,aes(color=re_af),
                   position = position_dodge(width = 0.75),parse=TRUE)+
  geom_point(data=ABC_sum,aes(x=re_af,y=average,color=re_af),
             position=position_dodge(0.6),width=0.6,stat="identity",size=3)+
  scale_shape_manual(values = c("4 yr, newly-sedimentary tidal flat, Vietnam (20.2°N)"=1,
                                 "5 yr, newly-sedimentary tidal flat, Vietnam (20.6°N)"=2,
                                 "6 yr, newly-sedimentary tidal flat, Vietnam (20.6°N)"=3,
                                 "3 yr, abandonded ponds, Vietnam (20.2°N)"=15,
                                 "3 yr, abandonded ponds, China (22.7°N)"=17,
                                 "5 yr, abandonded ponds, India (20.4°N)"=18))+
  mytheme+
  theme(
        axis.title.x=element_blank(),
        legend.title=element_blank(),
        legend.position = "bottom",
        panel.grid.major =element_blank(), 
        panel.grid.minor = element_blank())+
       ylab(expression(paste("Carbon density (Mg C ha"^-1*")")))+
      guides(
      shape = guide_legend(nrow = 3,
                                title="Detailed site information",
                                override.aes = list(size = c(2,2))))+
      ggtitle("Aboveground biomass carbon")

## BBC
ano=aov(BBC_mean~re_af,data=BBC)

plot(ano,1)
leveneTest(BBC_mean~re_af,data=BBC)

# normality of residuals
plot(ano, 2)
aov_residuals <- residuals(object = ano)
shapiro.test(x = aov_residuals)
## significant in the test of normality and homoscedasticity of model residuals


BBC_sum=BBC%>%group_by(re_af)%>%
  summarise(average = mean(BBC_mean),
                   std=sd(BBC_mean,na.rm = TRUE)/sqrt(length(BBC_mean)),
                   median=median(BBC_mean))%>%ungroup()

# function for number of observations 
give.n <- function(x){
  return(data.frame(y = 0.1, label =  paste('italic(n) ==', length(x))))
  # experiment with the multiplier to find the perfect position
}


P2=ggplot(data=BBC,aes(x=re_af,y=BBC_mean))+
  geom_jitter(data=BBC,aes(x=re_af,y=BBC_mean,size=Age,shape=ID),
                      color="grey",alpha=0.6,size=2,position = position_jitter(0.21))+
  stat_compare_means(size=2.5,aes(label = sprintf("italic(P)==%0.4f",as.numeric(..p.format..))),
                     label.x=1.5,show.legend = F,parse=TRUE)+
  stat_summary(aes(col = re_af), fun.data = "mean_se", geom = "errorbar", width=0.3)+
    stat_summary(fun.data = give.n, geom = "text", fun.y = median, size=2.5,aes(color=re_af),
                   position = position_dodge(width = 0.75),parse=TRUE)+
  geom_point(data=BBC_sum,aes(x=re_af,y=average,color=re_af),
             position=position_dodge(0.6),width=0.6,stat="identity",size=3)+
  scale_shape_manual(values = c( "3 yr, newly-sedimentary tidal flat, Vietnam (20.7°N)"=4,
                                 "4 yr, newly-sedimentary tidal flat, Vietnam (20.2°N)"=1,
                                 "5 yr, newly-sedimentary tidal flat, Vietnam (20.7°N)"=5,
                                 "3 yr, abandonded ponds, Vietnam (20.2°N)"=15,
                                 "3 yr, abandonded ponds, China (22.7°N)"=17,
                                 "5 yr, abandonded ponds, India (20.4°N)"=18))+
  mytheme+
  theme(axis.title.x=element_blank(),
        legend.title=element_blank(),
        legend.position = "bottom",
        panel.grid.major =element_blank(), 
        panel.grid.minor = element_blank())+
       ylab(expression(paste("Carbon density (Mg C ha"^-1*")")))+
      guides(
      shape = guide_legend(nrow = 3,
                                title="Detailed site information",
                                override.aes = list(size = c(2,2))))+
      ggtitle("Belowground biomass carbon")
    
P3=ggplot(data,aes(x=Age,y=BC_mean,shape=ID))+
      geom_point()+
      scale_shape_manual(values = c( "3 yr, newly-sedimentary tidal flat, Vietnam (20.7°N)"=4,
                                 "4 yr, newly-sedimentary tidal flat, Vietnam (20.2°N)"=1,
                                 "5 yr, newly-sedimentary tidal flat, Vietnam (20.7°N)"=5,
                                 "5 yr, newly-sedimentary tidal flat, Vietnam (20.6°N)"=2,
                                 "6 yr, newly-sedimentary tidal flat, Vietnam (20.6°N)"=3,
                                 "3 yr, abandonded ponds, Vietnam (20.2°N)"=15,
                                 "3 yr, abandonded ponds, China (22.7°N)"=17,
                                 "5 yr, abandonded ponds, India (20.4°N)"=18))+
      guides(color="none",
             shape = guide_legend(nrow = 5,
                                title="Detailed site information",
                                override.aes = list(size = c(2,2))))+
      mytheme+
      theme(
        axis.title.x=element_blank(), 
        legend.title=element_blank(),
        legend.text = element_text(size=7),
        legend.position = "bottom",
        panel.grid.major =element_blank(), 
        panel.grid.minor = element_blank())
    
leg = get_legend(P3)
    
P4=as_ggplot(leg)+
      theme(
              panel.background = element_rect(fill = "transparent",color=NA), 
        plot.background = element_rect(fill = "transparent", color = NA),
        panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        legend.background = element_rect(fill = "transparent", color = NA),
        panel.border = element_rect(fill = "transparent", color = NA),
        rect = element_rect(fill = "transparent")) 


ggarrange(ggarrange(P1,P2,nrow=1,labels=c("a","b"),legend="none",
                    font.label=list(family = "Helvetica",size=7)),P4,
          font.label=list(family = "Helvetica",size=2),
          nrow=2,heights=c(2,1),labels="")

ggsave("Fig.S8.png", 
       path ="[Please change it to your own path]",
         width = 150,height = 90,units = c("mm"),dpi = 300)

```


```{r}
data=read.csv("Supplementary Data.csv",stringsAsFactors = FALSE,fileEncoding="latin1")

data=data%>%
  filter(ID<1000)%>%  # delete abnormal data
  filter(re_af!="")%>%
  filter(Age<=40)

colnames(data)[c(19:24,26,28:33,35)]=c("BC_mean","ABC_mean","BBC_mean",
                                    "SCS_mean","SCS_mean_100","SCS_increase_all",
                                       "SC_mean","TECS_mean",
                                       "salinity_pore",
                                       "sand","silt","clay",
                                       "TN_mean","N.concentration_mean")  ## simplify column names


ABC=data %>% drop_na(ABC_mean)%>%filter(group=="restored")%>% 
  filter(Species!="")%>%
  filter(ABC_mean>0)%>%
  convert_as_factor(re_af,Species_2,plant_nature,climate.type_2)%>%mutate_all(type.convert)

ABC$rate=ABC$ABC_mean/ABC$Age


ABC$sm=ABC$Species_2
ABC$sm[ABC$sm!="Mixed"]="Single"

ABC$Species_2[ABC$Species_2=="RMu"|ABC$Species_2=="RMa"]="RM"
ABC$Species_2[ABC$Species_2=="RA"|ABC$Species_2=="RS"]="RA"
ABC$Species_2[ABC$Species_2=="KO"|ABC$Species_2=="KC"]="K"
ABC$Species_2[ABC$Species_2=="AM"|ABC$Species_2=="AA"]="A"
ABC$Species_2[ABC$Species_2=="SA"|ABC$Species_2=="SC"]="S"
ABC$Species_2[ABC$Species_2=="BS"|ABC$Species_2=="BG"]="B"

ABC$inter=interaction(ABC$ID,ABC$re_af,ABC$plant_nature,ABC$Species_2,ABC$sm)

ABC_1=ABC%>%filter(Age>15)

ll=lme4::lmList(ABC_mean~0+Age|inter, data=ABC)

L1=coef(ll)

n=t(as.data.frame(lapply(ll, function(x) rbind(nrow(x["model"]$model)))))

c= ABC %>% dplyr::group_by(inter) %>% dplyr::summarize(
                                        re_af=paste(unique(re_af), collapse = ', '),
                                        plant_nature = paste(unique(plant_nature), collapse = ', '),
                                        Species_2=paste(unique(Species_2), collapse = ', '),
                                        sm=paste(unique(sm), collapse = ', '),
                                        minAge=min(Age),
                                        maxAge=max(Age))

ABC_coef=cbind(L1,c,n)%>%filter(Age!="")%>%filter(n>1)


ggboxplot(ABC_1,x="re_af",y="rate",
          color = "re_af", 
          add = "jitter", 
          legend = "none")+stat_compare_means(size=5)+
  theme_bw()+
  stat_compare_means(size=5)+
    theme(axis.text.x=element_blank(), 
        axis.text.y=element_text(face="plain",colour="black",size=15), 
        axis.title.y=element_text(face="plain",size=15), 
        axis.title.x=element_text(face="plain",color="white",size=15), 
        plot.title=element_text(hjust=0.5,size=15,colour = "white"),
        legend.title=element_blank(),
        legend.text = element_text(face="plain",color="black",size=15), 
        # legend.position = "none",
        panel.grid.major =element_blank(), 
        panel.grid.minor = element_blank())+
    ylab(expression(paste("Mean Annual Increment / Mg C ha"^-1 *"yr"^-1)))
  
ABC_coef_1=ABC_coef%>%filter(Species_2!="Mixed")


ano=kruskal.test(rate~Species_2,data=ABC_1)
DT=dunnTest(rate~Species_2,data=ABC_1,method="bonferroni")
PT=DT$res
a=cldList(P.adj ~ Comparison,
        data = PT,
        threshold = 0.05)

ABC_coef_1_mean = ABC_1 %>% 
  dplyr::group_by(Species_2) %>% 
  dplyr::summarize(average = mean(rate),
                   std=sd(rate,na.rm = TRUE)/sqrt(length(rate)),
                   median=median(rate)) %>%
  arrange(desc(average))%>%
  ungroup()
ABC_coef_1_mean$cl=a$Letter

ggboxplot(ABC_1,x="Species_2",y="rate",
          color = "Species_2", 
          add = "jitter", 
          legend = "none")+
  theme_bw()+
  geom_text(data = ABC_coef_1_mean, aes(x = Species_2, y = 13, label = cl,color=Species_2), 
            size = 5,show.legend = F)+
    theme(axis.text.x=element_blank(), 
        axis.text.y=element_text(face="plain",colour="black",size=15), 
        axis.title.y=element_text(face="plain",size=15), 
        axis.title.x=element_text(face="plain",color="white",size=15), 
        plot.title=element_text(hjust=0.5,size=15,colour = "white"),
        legend.title=element_blank(),
        legend.text = element_text(face="plain",color="black",size=15), 
        # legend.position = "none",
        panel.grid.major =element_blank(), 
        panel.grid.minor = element_blank())+
    ylab(expression(paste("Mean Annual Increment / Mg C ha"^-1 *"yr"^-1)))


ggboxplot(ABC_1,x="plant_nature",y="rate",
          color = "plant_nature", 
          add = "jitter", 
          legend = "none")+stat_compare_means(size=5)+
  theme_bw()+
  stat_compare_means(size=5)+
    theme(axis.text.x=element_blank(), 
        axis.text.y=element_text(face="plain",colour="black",size=15), 
        axis.title.y=element_text(face="plain",size=15), 
        axis.title.x=element_text(face="plain",color="white",size=15), 
        plot.title=element_text(hjust=0.5,size=15,colour = "white"),
        legend.title=element_blank(),
        legend.text = element_text(face="plain",color="black",size=15), 
        # legend.position = "none",
        panel.grid.major =element_blank(), 
        panel.grid.minor = element_blank())+
    ylab(expression(paste("Mean Annual Increment / Mg C ha"^-1 *"yr"^-1)))

ggboxplot(ABC_1,x="sm",y="rate",
          color = "sm", 
          add = "jitter", 
          legend = "none")+stat_compare_means(size=5)+
  theme_bw()+
  stat_compare_means(size=5)+
    theme(axis.text.x=element_blank(), 
        axis.text.y=element_text(face="plain",colour="black",size=15), 
        axis.title.y=element_text(face="plain",size=15), 
        axis.title.x=element_text(face="plain",color="white",size=15), 
        plot.title=element_text(hjust=0.5,size=15,colour = "white"),
        legend.title=element_blank(),
        legend.text = element_text(face="plain",color="black",size=15), 
        # legend.position = "none",
        panel.grid.major =element_blank(), 
        panel.grid.minor = element_blank())+
    ylab(expression(paste("Mean Annual Increment / Mg C ha"^-1 *"yr"^-1)))

```


